import {COMPOSITION_BY_ID} from '../../data/neurohero/compositions.mjs';
export const PORTRAIT_SPEC_VERSION='cc-portrait-spec-1.1';
export const PORTRAIT_OPTIONS={
 presentation:['woman','man','androgynous','armored','emblem'],
 skinTone:['very-light','light','medium','tan','deep','very-deep','not-specified'],
 build:['slender','average','athletic','broad','soft','not-specified'],
 hair:['short','medium','long','curly','coiled','shaved','covered','not-specified'],
 accessibility:['none-specified','wheelchair','cane','prosthetic-limb','hearing-device','not-specified'],
 setting:['night-city','mountain-observatory','coastal-lab','quiet-library','abstract-compass-space'],
};
const MOTIFS={mapping:['layered translucent maps','a handheld instrument resolving scattered lights into a navigable path'],navigation:['a luminous compass lattice','branching paths becoming a clear route'],creation:['modular tools','floating geometric pieces assembling into a working form'],craft:['precision instruments','a focused workbench with a single illuminated project'],adaptation:['reconfigurable panels','a path that changes shape without losing its destination'],protection:['a translucent boundary field','a calm protected workspace'],connection:['paired signal lights','bridges connecting distinct islands of information'],discernment:['a calibrated lens','separate markers for signal, uncertainty, and safety'],memory:['layered memory cards','context markers linked across time'],systems:['a network map','interlocking systems shown with clear boundaries'],recovery:['a tide-like light field','a restorative chamber with adjustable intensity'],opportunity:['small lights indicating emerging openings','a scanner highlighting a few high-value paths'],precision:['measurement tools','fine alignment marks and a stabilized control surface'],discovery:['an exploratory lens','deep layers opening into unexpected connections'],social:['conversation glyphs without text','multiple viewpoints aligned around a shared map'],story:['constellations of remembered details','threads forming several possible narratives'],attention:['a movable spotlight','competing signals sorted into priorities'],stability:['a navigable shelter','clear gates and supportive guide lights'],direction:['a central compass rose','distinct zones separated through color and shape'],meaning:['emotion-colored glass','several interpretations held side by side'],perception:['a calibrated signal lens','subtle changes separated from background noise'],execution:['modular construction rails','an adaptable route from plan to finished form']};
const defaults={presentation:'emblem',skinTone:'not-specified',build:'not-specified',hair:'not-specified',accessibility:'none-specified',setting:'abstract-compass-space'};
const valid=(group,value)=>PORTRAIT_OPTIONS[group].includes(value)?value:defaults[group];
export function normalizePortraitChoices(raw={}){const result={};const input=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{};for(const key of Object.keys(PORTRAIT_OPTIONS))result[key]=valid(key,Object.hasOwn(input,key)?input[key]:undefined);return result;}
export function compilePortraitBrief(profile,raw={}){const c=normalizePortraitChoices(raw),hero=Object.hasOwn(COMPOSITION_BY_ID,profile?.signature?.id||'')?COMPOSITION_BY_ID[profile.signature.id]:null,theme=hero?.theme||'direction',motifs=MOTIFS[theme]||MOTIFS.direction;const subject=c.presentation==='emblem'?'a symbolic nonhuman Cortex Compass emblem':`an original adult ${c.presentation==='not-specified'?'androgynous':c.presentation} hero`;const details=[c.skinTone!=='not-specified'?`${c.skinTone.replaceAll('-',' ')} skin tone`:null,c.build!=='not-specified'?`${c.build} build`:null,c.hair!=='not-specified'?`${c.hair.replaceAll('-',' ')} hair`:null,c.accessibility&&!['none-specified','not-specified'].includes(c.accessibility)?c.accessibility.replaceAll('-',' '):null].filter(Boolean).join(', ');return {version:PORTRAIT_SPEC_VERSION,heroId:hero?.id||'unclassified',theme,title:hero?.name||'Cortex Compass Explorer',choices:c,motifs,subject,details};}
export function compileImagePrompt(profile,raw={}){const b=compilePortraitBrief(profile,raw),setting=b.choices.setting.replaceAll('-',' ');return `Create an original highly detailed anime-inspired adult hero portrait for Cortex Compass. ${b.subject}${b.details?`, ${b.details}`:''}. Hero concept: ${b.title}. Visual theme: ${b.theme}. Include these symbolic motifs: ${b.motifs.join('; ')}. Setting: ${setting}. Deep navy woven materials, sea-glass illumination, restrained brass details, grounded capable posture, expressive humane face, relatable proportions, cinematic three-quarter composition, clean silhouette, generous negative space for separately typeset report content. No text, logos from other brands, clinical imagery, wounds, trauma scenes, diagnostic symbols, or existing franchise characters. This is fictional symbolic artwork and must not imply measured brain anatomy.`;}
