import {generateXaiPortrait,normalizeVisualSpec,visualFingerprint,sha256,XAI_CONFIG,PortraitError} from './xai.mjs';
const COOKIE='__Host-cc-portrait';const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const token=()=>btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32)))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const constantEqual=(a,b)=>{if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0;};
const json=(data,status=200,headers={})=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff',...headers}});
async function readJSON(request,fields){if(!request.headers.get('content-type')?.startsWith('application/json'))throw new PortraitError('json_required',415);const reader=request.body?.getReader();if(!reader)throw new PortraitError('body_required');let size=0,text='';const decoder=new TextDecoder();for(;;){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>8192){await reader.cancel();throw new PortraitError('request_too_large',413);}text+=decoder.decode(r.value,{stream:true});}text+=decoder.decode();let data;try{data=JSON.parse(text);}catch{throw new PortraitError('invalid_json');}if(!data||typeof data!=='object'||Array.isArray(data)||Object.keys(data).some(k=>!fields.includes(k)))throw new PortraitError('unsupported_fields');return data;}
function cookieValue(request){const match=request.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(COOKIE+'='));const value=match?.slice(COOKIE.length+1);return value&&/^[A-Za-z0-9_-]{43}$/.test(value)?value:null;}
const setCookie=(value,maxAge=604800)=>`${COOKIE}=${value}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Strict`;
function accessEntries(env){try{return JSON.parse(env.CORTEX_PORTRAIT_ACCESS||'[]').filter(x=>UUID.test(x.account)&&/^[a-f0-9]{64}$/.test(x.hash)&&Number.isFinite(x.expires)&&x.expires>Date.now()&&Number.isInteger(x.limit)&&x.limit>0&&x.limit<=25);}catch{return [];}}
const publicJob=j=>({id:j.id,status:j.status,createdAt:j.createdAt,spec:j.spec||null,error:j.error||null,progress:j.progress||null,...(j.status==='ready'?{sha256:j.sha256,contentType:j.contentType,bytes:j.bytes,model:j.model}:{}),provider:'xAI'});
export class PortraitService{
 constructor(ctx,env){this.ctx=ctx;this.env=env;this.store=ctx.storage;}
 async session(request){const value=cookieValue(request);if(!value)return null;const key=await sha256(value),s=await this.store.get('session:'+key);if(!s||s.expires<=Date.now())return null;const grant=accessEntries(this.env).find(e=>e.account===s.account);return grant&&s.grantHash===grant.hash?{...s,key,grant}:null;}
 async schedule(when=Date.now()+100){const alarm=await this.store.getAlarm();if(alarm===null||when<alarm)await this.store.setAlarm(when);}
 async login(request){const body=await readJSON(request,['pass']);const ip=request.headers.get('CF-Connecting-IP')||'local';const slot=Math.floor(Date.now()/900000);const key='rate:'+slot+':'+await sha256(ip+'|'+this.env.CORTEX_PORTRAIT_RATE_SALT);
 const allowed=await this.store.transaction(async tx=>{const n=await tx.get(key)||0,g=await tx.get('login-rate:'+slot)||0;if(n>=12||g>=120)return false;await tx.put(key,n+1);await tx.put('login-rate:'+slot,g+1);return true;});if(!allowed)throw new PortraitError('try_later',429);
 if(typeof body.pass!=='string'||!/^[A-Za-z0-9_-]{43}$/.test(body.pass))throw new PortraitError('access_not_available',401);const digest=await sha256(body.pass);const grant=accessEntries(this.env).find(e=>constantEqual(e.hash,digest));if(!grant)throw new PortraitError('access_not_available',401);
 const value=token(),session={account:grant.account,grantHash:grant.hash,expires:Math.min(Date.now()+604800000,grant.expires)};await this.store.put('session:'+await sha256(value),session);await this.schedule(Date.now()+86400000);return json({authenticated:true,accessMode:'private-pilot'},200,{'Set-Cookie':setCookie(value)});}
 async status(request){const s=await this.session(request);if(!s)return json({available:true,authenticated:false,provider:'xAI',accessMode:'private-pilot',requiresAccessPass:true});const used=await this.store.get('count:'+s.account)||0;const records=await this.store.list({prefix:'job:'+s.account+':'});return json({available:true,authenticated:true,provider:'xAI',model:XAI_CONFIG.model,quality:XAI_CONFIG.quality,resolution:XAI_CONFIG.resolution,remaining:Math.max(0,s.grant.limit-used),jobs:[...records.values()].filter(j=>!['deleted','deleting'].includes(j.status)).map(publicJob).sort((a,b)=>b.createdAt-a.createdAt)});}
 async fetch(request){try{
 const url=new URL(request.url);if(url.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(url.hostname))throw new PortraitError('https_required',426);const path=url.pathname.replace(/^\/api\/portraits/,'');
 if(!this.env.CORTEX_XAI_API_KEY||!this.env.CORTEX_PORTRAIT_RATE_SALT||!this.env.PORTRAIT_IMAGES||!accessEntries(this.env).length)return json({available:false,error:'service_not_configured'},503);
 if(!['GET','POST','DELETE'].includes(request.method))throw new PortraitError('method_not_allowed',405);
 if(request.method!=='GET'&&(request.headers.get('Origin')!==url.origin||request.headers.get('X-Cortex-Request')!=='portrait-v1'))throw new PortraitError('request_origin_rejected',403);
 if(path==='/status'&&request.method==='GET')return await this.status(request);
 if(path==='/session'&&request.method==='POST')return await this.login(request);
 const s=await this.session(request);if(!s)throw new PortraitError('sign_in_required',401);
 if(path==='/session'&&request.method==='DELETE'){await this.store.delete('session:'+s.key);return json({authenticated:false},200,{'Set-Cookie':setCookie('',0)});}
 if(path==='/jobs'&&request.method==='POST')return await this.createJob(request,s);
 const match=path.match(/^\/jobs\/([a-f0-9-]{36})(\/image)?$/);if(!match||!UUID.test(match[1]))throw new PortraitError('not_found',404);return await this.jobAction(request,s,match[1],Boolean(match[2]));
 }catch(e){return json({error:e instanceof PortraitError?e.code:'service_error'},e instanceof PortraitError?e.status:500);}}
 async createJob(request,s){const body=await readJSON(request,['spec','requestId','consent']);if(body.consent!==true)throw new PortraitError('consent_required');if(!UUID.test(body.requestId||''))throw new PortraitError('request_id_required');const spec=normalizeVisualSpec(body.spec),fingerprint=await visualFingerprint(spec);const day=new Date().toISOString().slice(0,10);
 const job=await this.store.transaction(async tx=>{const requestKey='request:'+s.account+':'+body.requestId;const previous=await tx.get(requestKey);if(previous){if(previous.fingerprint!==fingerprint)throw new PortraitError('idempotency_conflict',409);const oldJob=await tx.get('job:'+s.account+':'+previous.id);if(oldJob?.status==='deleted')throw new PortraitError('edition_deleted',409);return oldJob;}
 const cached=await tx.get('spec:'+s.account+':'+fingerprint);if(cached){const j=await tx.get('job:'+s.account+':'+cached);if(j?.status==='deleted')throw new PortraitError('edition_deleted',409);await tx.put(requestKey,{id:j.id,fingerprint});return j;}
 const count=await tx.get('count:'+s.account)||0,total=await tx.get('total-attempts')||0,daily=await tx.get('day:'+day)||0;
 const configured=Number(this.env.PORTRAIT_TOTAL_LIMIT??100);const cap=Number.isFinite(configured)?Math.min(100,Math.max(0,Math.floor(configured))):0;if(count>=s.grant.limit)throw new PortraitError('portrait_allowance_used',429);if(total>=cap||daily>=25)throw new PortraitError('pilot_budget_reached',429);
 const j={id:crypto.randomUUID(),account:s.account,status:'queued',spec,fingerprint,createdAt:Date.now()};const key='job:'+s.account+':'+j.id;const queue=await tx.get('queue')||[];
 await tx.put(key,j);await tx.put(requestKey,{id:j.id,fingerprint});await tx.put('spec:'+s.account+':'+fingerprint,j.id);await tx.put('queue',[...queue,key]);await tx.put('count:'+s.account,count+1);await tx.put('total-attempts',total+1);await tx.put('day:'+day,daily+1);return j;});
 if(job.status==='queued')await this.schedule();return json({job:publicJob(job),reused:job.status!=='queued'},job.status==='queued'?202:200);}
 async jobAction(request,s,id,isImage){const key='job:'+s.account+':'+id,j=await this.store.get(key);if(!j||['deleted','deleting'].includes(j.status))throw new PortraitError('not_found',404);
 if(request.method==='GET'&&isImage){if(j.status!=='ready')throw new PortraitError('portrait_not_ready',409);const image=await this.env.PORTRAIT_IMAGES.get(s.account+'/'+id);if(!image)throw new PortraitError('portrait_missing',404);return new Response(image.body,{headers:{'Content-Type':j.contentType,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Disposition':'inline; filename="Cortex-Compass-Hero"','X-Portrait-SHA256':j.sha256}});}
 if(request.method==='GET')return json({job:publicJob(j)});
 if(request.method==='DELETE'&&!isImage){const state=await this.store.transaction(async tx=>{const current=await tx.get(key);if(!current||current.status==='deleted')throw new PortraitError('not_found',404);const status=current.status==='running'?'running':'deleting';await tx.put(key,{...current,status,deleteRequested:true});return status;});if(state==='running')return json({deletionPending:true},202);await this.env.PORTRAIT_IMAGES.delete(s.account+'/'+id);await this.finish(key,{status:'deleted',spec:null});return json({deleted:true});}
 throw new PortraitError('method_not_allowed',405);}
 async finish(key,patch){await this.store.transaction(async tx=>{const j=await tx.get(key);if(j){const removed=j.deleteRequested||['deleted','deleting'].includes(j.status)||patch.status==='deleted';await tx.put(key,removed?{id:j.id,account:j.account,status:'deleted',createdAt:j.createdAt}:{...j,...patch});}const queue=await tx.get('queue')||[];await tx.put('queue',queue.filter(k=>k!==key));});}
 async alarm(){const queue=await this.store.get('queue')||[];const key=queue[0];if(!key){await this.cleanup();return;}let j=await this.store.get(key);
 if(j?.status==='deleting'){await this.env.PORTRAIT_IMAGES.delete(j.account+'/'+j.id);await this.finish(key,{status:'deleted',spec:null});await this.store.setAlarm(Date.now()+100);return;}
 if(!j||j.status==='deleted'){await this.finish(key,{});const q=await this.store.get('queue')||[];if(q.length)await this.store.setAlarm(Date.now()+100);return;}
 // Persist running BEFORE any paid call. An alarm retry never resubmits an uncertain provider request.
 if(j.status==='running'){const stored=await this.env.PORTRAIT_IMAGES.head(j.account+'/'+j.id);if(stored&&!j.deleteRequested){await this.finish(key,{status:'ready',sha256:stored.customMetadata.sha256,contentType:stored.httpMetadata.contentType,bytes:stored.size,model:stored.customMetadata.model});}else{if(stored)await this.env.PORTRAIT_IMAGES.delete(j.account+'/'+j.id);await this.finish(key,{status:j.deleteRequested?'deleted':'failed',error:'provider_outcome_unknown',spec:j.deleteRequested?null:j.spec});}await this.store.setAlarm(Date.now()+100);return;}
 if(j.status!=='queued'){await this.finish(key,{});await this.store.setAlarm(Date.now()+100);return;}
 j={...j,status:'running',startedAt:Date.now()};await this.store.put(key,j);await this.store.setAlarm(Date.now()+240000);
 try{const image=await generateXaiPortrait(j.spec,{apiKey:this.env.CORTEX_XAI_API_KEY,onProgress:async progress=>{const latest=await this.store.get(key);if(latest)await this.store.put(key,{...latest,progress});}});const latest=await this.store.get(key);if(latest?.deleteRequested){await this.finish(key,{status:'deleted',spec:null});}else{
 await this.env.PORTRAIT_IMAGES.put(j.account+'/'+j.id,image.bytes,{httpMetadata:{contentType:image.contentType,cacheControl:'private, no-store'},customMetadata:{sha256:image.sha256,model:image.model,style:image.styleVersion}});
 const after=await this.store.get(key);if(after?.deleteRequested){await this.env.PORTRAIT_IMAGES.delete(j.account+'/'+j.id);await this.finish(key,{status:'deleted',spec:null});}else await this.finish(key,{status:'ready',sha256:image.sha256,contentType:image.contentType,bytes:image.bytes.length,model:image.model,completedAt:Date.now()});}}
 catch(e){const latest=await this.store.get(key);await this.finish(key,{status:latest?.deleteRequested?'deleted':'failed',error:e instanceof PortraitError?e.code:'provider_outcome_unknown',spec:latest?.deleteRequested?null:j.spec});}
 const left=await this.store.get('queue')||[];await this.store.setAlarm(Date.now()+(left.length?100:86400000));}
 async cleanup(){const now=Date.now(),slot=Math.floor(now/900000);for(const prefix of ['session:','rate:','login-rate:']){const rows=await this.store.list({prefix,limit:1000});const expired=[];for(const [key,value] of rows){if(prefix==='session:'?value.expires<=now:Number(key.split(':')[1])<slot-1)expired.push(key);}if(expired.length)await this.store.delete(expired);}if((await this.store.list({prefix:'session:',limit:1})).size)await this.store.setAlarm(now+86400000);}
}
