import test from 'node:test';
import assert from 'node:assert/strict';
import {HERO_PROCESSES,SAMPLE_HERO_ANSWERS} from '../src/data/neurohero/processes.mjs';
import {SAMPLE_INSIGHTS} from '../src/data/insightQuestions.mjs';
import {NEURO_SYSTEMS} from '../src/data/neurograph/systems.mjs';
import {OBSERVATION_NODES,CONSTRUCT_NODES} from '../src/data/neurograph/model.mjs';
import {EVIDENCE_RECORDS} from '../src/data/neurograph/evidenceRegistry.mjs';
import {validateGraph,classifyPair,hypothesisSpace} from '../src/utils/neurograph/graphEngine.mjs';
import {buildNeurocompositionProfile} from '../src/utils/neurograph/compositionEngine.mjs';
import {buildDeepNeurograph} from '../src/utils/neurograph/profileEngine.mjs';
import {compositionSupport,observationFit} from '../src/utils/neurograph/confidenceEngine.mjs';
test('graph resolves and is materially deeper than the original hero list',()=>{const g=validateGraph();assert.equal(g.ok,true);assert.ok(g.nodeCount>=130);assert.ok(g.edgeCount>=200);assert.equal(g.pairPotentialities,351);});
test('every original functional observation maps to exactly one functional system',()=>{assert.equal(OBSERVATION_NODES.length,HERO_PROCESSES.length);assert.equal(new Set(OBSERVATION_NODES.map(x=>x.id)).size,HERO_PROCESSES.length);assert.ok(OBSERVATION_NODES.every(x=>NEURO_SYSTEMS.some(s=>s.id===x.systemId)));});
test('research constructs are context-only and never presented as personal measurements',()=>{assert.ok(CONSTRUCT_NODES.length>=40);assert.ok(CONSTRUCT_NODES.every(x=>x.measurement==='research construct only'));});
test('evidence registry combines method, development and hero records without duplicate ids',()=>{assert.ok(EVIDENCE_RECORDS.length>=20);assert.equal(new Set(EVIDENCE_RECORDS.map(x=>x.id)).size,EVIDENCE_RECORDS.length);assert.ok(EVIDENCE_RECORDS.every(x=>x.limit&&x.url));});
test('sample produces a traceable functional fit without claiming a neural measurement',()=>{const p=buildDeepNeurograph(SAMPLE_HERO_ANSWERS,SAMPLE_INSIGHTS,'signal_cartographer');assert.equal(p.selected.id,'signal_cartographer');assert.ok(p.selected.supportIndex>.8);assert.equal(p.selected.neuralStatus,'not-measured');assert.equal(p.selected.probability,false);assert.equal(p.selectedExplanation.unknown.length,3);});
test('empty input cannot manufacture a graph profile',()=>{const p=buildNeurocompositionProfile({});assert.equal(p.active.length,0);assert.equal(p.namedCompositions.length,0);assert.equal(p.selected,null);});
test('non-functional fields cannot alter composition ranking',()=>{const base=buildNeurocompositionProfile(SAMPLE_HERO_ANSWERS);const extra=buildNeurocompositionProfile({...SAMPLE_HERO_ANSWERS,sexAssigned:'female',genderIdentity:'woman',age:40});assert.deepEqual(extra.namedCompositions,base.namedCompositions);assert.deepEqual(extra.systems,base.systems);});
test('a frequent counterexample removes a required process from named compositions',()=>{const raw=structuredClone(SAMPLE_HERO_ANSWERS);raw.signal_detection={value:'often',counter:'often'};const p=buildNeurocompositionProfile(raw);assert.ok(!p.namedCompositions.some(x=>x.id==='signal_cartographer'));});
test('counterexample review is monotonic',()=>{const missing=observationFit({value:'often'}),reviewed=observationFit({value:'often',counter:'rarely'}),qualified=observationFit({value:'often',counter:'sometimes'});assert.ok(reviewed.fit>missing.fit);assert.ok(qualified.fit<reviewed.fit);assert.ok(reviewed.fit<=1);});
