import test from 'node:test';
import assert from 'node:assert/strict';
import {generateXaiPortrait,normalizeVisualSpec,portraitRequest,visualFingerprint,sha256,XAI_CONFIG} from '../worker/portraits/xai.mjs';
import {PortraitService} from '../worker/portraits/service.mjs';
const origin='https://cortexcompass.utlyze.com';
const spec={heroId:'signal_cartographer',choices:{presentation:'woman',skinTone:'medium',hair:'curly',setting:'mountain-observatory'},edition:0};
class MemoryStorage{
 constructor(){this.map=new Map();this.alarm=null;this.tail=Promise.resolve();}
 async get(k){return structuredClone(this.map.get(k));}async put(k,v){this.map.set(k,structuredClone(v));}
 async delete(k){for(const id of Array.isArray(k)?k:[k])this.map.delete(id);}
 async list({prefix='',limit=10000}={}){return new Map([...this.map].filter(([k])=>k.startsWith(prefix)).sort(([a],[b])=>a.localeCompare(b)).slice(0,limit).map(([k,v])=>[k,structuredClone(v)]));}
 async getAlarm(){return this.alarm;}async setAlarm(at){this.alarm=at;}
 transaction(fn){const run=this.tail.then(async()=>{const snapshot=structuredClone(this.map);try{return await fn(this);}catch(e){this.map=snapshot;throw e;}});this.tail=run.catch(()=>{});return run;}
}
class Bucket{constructor(){this.map=new Map();}async put(k,b,opt){this.map.set(k,{bytes:new Uint8Array(b),...opt});}async get(k){const r=this.map.get(k);return r?{body:r.bytes,...r,size:r.bytes.length}:null;}async head(k){return this.get(k);}async delete(k){this.map.delete(k);}}
async function fixture(limit=3,total=100){const a=crypto.randomUUID(),b=crypto.randomUUID();const access=[{account:a,hash:await sha256('A'.repeat(43)),limit,expires:Date.now()+86400000},{account:b,hash:await sha256('B'.repeat(43)),limit,expires:Date.now()+86400000}];const store=new MemoryStorage(),bucket=new Bucket();const env={CORTEX_XAI_API_KEY:'fixture-not-a-real-key',CORTEX_PORTRAIT_ACCESS:JSON.stringify(access),CORTEX_PORTRAIT_RATE_SALT:'test-only-salt',PORTRAIT_IMAGES:bucket,PORTRAIT_TOTAL_LIMIT:String(total)};const service=new PortraitService({storage:store},env);return {service,store,bucket,env,a,b};}
async function request(f,path,method='GET',body,cookie='',headers={}){return f.service.fetch(new Request(origin+'/api/portraits'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','X-Cortex-Request':'portrait-v1',...(cookie?{Cookie:cookie}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})}));}
async function login(f,pass='A'.repeat(43)){const r=await request(f,'/session','POST',{pass});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];}
const makeJob=(f,cookie,visual=spec,id=crypto.randomUUID())=>request(f,'/jobs','POST',{spec:visual,requestId:id,consent:true},cookie);
const image=()=>{const b=new Uint8Array(900);b.set([255,216,255,224]);return {data:[{b64_json:btoa(String.fromCharCode(...b)),respect_moderation:true}],model:'grok-imagine-image-2.0'};};
test('model, quality, resolution and count pinned server side',()=>assert.deepEqual(XAI_CONFIG,{model:'grok-imagine-image-2.0',quality:'medium',resolution:'2k',aspect_ratio:'3:4',n:1,response_format:'b64_json'}));
test('prompt only uses approved visual fields',()=>{const r=portraitRequest(spec);assert.match(r.prompt,/2D anime/);assert.match(r.prompt,/original adult woman/);assert.equal(r.n,1);assert.doesNotMatch(r.prompt,/api_key|childhood answers/);});
for(const extra of ['history','diagnosis','email','prompt','model','n'])test(`visual schema rejects ${extra}`,()=>assert.throws(()=>normalizeVisualSpec({...spec,[extra]:'private'})));
test('unknown hero and unrecognized nested appearance are refused',()=>{assert.throws(()=>normalizeVisualSpec({...spec,heroId:'private history'}));assert.throws(()=>normalizeVisualSpec({...spec,choices:{...spec.choices,diagnosis:'x'}}));assert.throws(()=>normalizeVisualSpec({...spec,choices:{presentation:'minor'}}));});
test('same art specification hashes deterministically, edition is explicit',async()=>{assert.equal(await visualFingerprint(spec),await visualFingerprint(structuredClone(spec)));assert.notEqual(await visualFingerprint(spec),await visualFingerprint({...spec,edition:1}));});
test('provider uses exact endpoint and returns bounded raster bytes',async()=>{let calls=0;const r=await generateXaiPortrait(spec,{apiKey:'fixture',fetchImpl:async(url,opt)=>{calls++;assert.equal(url,'https://api.x.ai/v1/images/generations');assert.equal(opt.headers.Authorization,'Bearer fixture');assert.equal(JSON.parse(opt.body).n,1);return Response.json(image());}});assert.equal(calls,1);assert.equal(r.bytes.length,900);assert.equal(r.contentType,'image/jpeg');assert.equal(r.sha256.length,64);});
test('explicit moderation failure is never retried',async()=>{let n=0;await assert.rejects(generateXaiPortrait(spec,{apiKey:'fixture',fetchImpl:async()=>{n++;return Response.json({data:[{...image().data[0],respect_moderation:false}]});}}),/image_filtered/);assert.equal(n,1);});
test('provider error text is not reflected to users',async()=>{await assert.rejects(generateXaiPortrait(spec,{apiKey:'fixture',fetchImpl:async()=>new Response('private provider detail',{status:403})}),/provider_access_denied/);});
test('network uncertainty does not cause a second paid request',async()=>{let n=0;await assert.rejects(generateXaiPortrait(spec,{apiKey:'fixture',fetchImpl:async()=>{n++;throw new Error('timeout');}}),/provider_outcome_unknown/);assert.equal(n,1);});
test('unauthenticated clients cannot start paid jobs or retrieve images',async()=>{const f=await fixture();assert.equal((await makeJob(f,'')).status,401);assert.equal((await request(f,'/jobs/'+crypto.randomUUID()+'/image')).status,401);assert.equal(await f.store.get('total-attempts'),undefined);});
test('cross-origin mutations are rejected before auth work',async()=>{const f=await fixture();assert.equal((await request(f,'/session','POST',{pass:'A'.repeat(43)},'',{Origin:'https://evil.example'})).status,403);});
test('login yields only an HttpOnly Secure strict cookie, no token in JSON',async()=>{const f=await fixture(),r=await request(f,'/session','POST',{pass:'A'.repeat(43)});assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Strict/);assert.deepEqual(await r.json(),{authenticated:true,accessMode:'private-pilot'});});
test('invalid pass is rejected and throttled',async()=>{const f=await fixture();for(let i=0;i<12;i++)assert.equal((await request(f,'/session','POST',{pass:'Z'.repeat(43)})).status,401);assert.equal((await request(f,'/session','POST',{pass:'Z'.repeat(43)})).status,429);});
test('signout invalidates the server session',async()=>{const f=await fixture(),c=await login(f);assert.equal((await request(f,'/session','DELETE',null,c)).status,200);assert.equal((await makeJob(f,c)).status,401);});
test('revoking a pass invalidates existing sessions',async()=>{const f=await fixture(),c=await login(f);const access=JSON.parse(f.env.CORTEX_PORTRAIT_ACCESS);access[0].hash='0'.repeat(64);f.env.CORTEX_PORTRAIT_ACCESS=JSON.stringify(access);assert.equal((await makeJob(f,c)).status,401);});
test('explicit provider-processing consent required',async()=>{const f=await fixture(),c=await login(f);assert.equal((await request(f,'/jobs','POST',{spec,requestId:crypto.randomUUID(),consent:false},c)).status,400);assert.equal(await f.store.get('total-attempts'),undefined);});
test('concurrent identical requests reserve one image only',async()=>{const f=await fixture(),c=await login(f),id=crypto.randomUUID();const results=await Promise.all(Array.from({length:12},()=>makeJob(f,c,spec,id).then(r=>r.json())));assert.equal(new Set(results.map(r=>r.job.id)).size,1);assert.equal(await f.store.get('total-attempts'),1);});
test('new request IDs for the same visual spec reuse the existing job',async()=>{const f=await fixture(),c=await login(f);const a=await (await makeJob(f,c)).json(),b=await (await makeJob(f,c)).json();assert.equal(a.job.id,b.job.id);assert.equal(await f.store.get('count:'+f.a),1);});
test('same request ID with a different specification is a conflict',async()=>{const f=await fixture(),c=await login(f),id=crypto.randomUUID();await makeJob(f,c,spec,id);assert.equal((await makeJob(f,c,{...spec,edition:1},id)).status,409);});
test('concurrent different specs cannot exceed account allowance',async()=>{const f=await fixture(3),c=await login(f);const results=await Promise.all(Array.from({length:10},(_,edition)=>makeJob(f,c,{...spec,edition})));assert.equal(results.filter(r=>r.status===202).length,3);assert.equal(await f.store.get('total-attempts'),3);});
test('global budget cannot be exceeded across accounts',async()=>{const f=await fixture(5,2),a=await login(f),b=await login(f,'B'.repeat(43));const r=await Promise.all([makeJob(f,a),makeJob(f,b),makeJob(f,a,{...spec,edition:1})]);assert.equal(r.filter(x=>x.status===202).length,2);});
test('zero budget disables new generation rather than restoring a default',async()=>{const f=await fixture(5,0),c=await login(f);assert.equal((await makeJob(f,c)).status,429);});
test('private job identifiers cannot cross workspace boundaries',async()=>{const f=await fixture(),a=await login(f),b=await login(f,'B'.repeat(43));const {job}=await (await makeJob(f,a)).json();for(const suffix of ['', '/image'])assert.equal((await request(f,'/jobs/'+job.id+suffix,'GET',null,b)).status,404);assert.equal((await request(f,'/jobs/'+job.id,'DELETE',null,b)).status,404);});
test('alarm generates once, private image retrieval reuses bytes',async t=>{const f=await fixture(),c=await login(f);const {job}=await (await makeJob(f,c)).json();let count=0;const old=globalThis.fetch;globalThis.fetch=async()=>{count++;return Response.json(image());};t.after(()=>globalThis.fetch=old);await f.service.alarm();await f.service.alarm();assert.equal(count,1);const r=await request(f,'/jobs/'+job.id+'/image','GET',null,c);assert.equal(r.status,200);assert.equal((await r.arrayBuffer()).byteLength,900);assert.equal(r.headers.get('cache-control'),'private, no-store');assert.equal(await f.store.get('total-attempts'),1);});
test('recovered running job never calls the provider again',async t=>{const f=await fixture(),c=await login(f);const {job}=await (await makeJob(f,c)).json();const key='job:'+f.a+':'+job.id;await f.store.put(key,{...await f.store.get(key),status:'running'});const old=globalThis.fetch;globalThis.fetch=async()=>{throw new Error('must not call');};t.after(()=>globalThis.fetch=old);await f.service.alarm();assert.equal((await f.store.get(key)).error,'provider_outcome_unknown');});
test('completed private storage can be recovered after a worker interruption',async()=>{const f=await fixture(),c=await login(f);const {job}=await (await makeJob(f,c)).json();const key='job:'+f.a+':'+job.id;await f.store.put(key,{...await f.store.get(key),status:'running'});await f.bucket.put(f.a+'/'+job.id,new Uint8Array(900),{httpMetadata:{contentType:'image/jpeg'},customMetadata:{sha256:'a'.repeat(64),model:XAI_CONFIG.model}});await f.service.alarm();assert.equal((await f.store.get(key)).status,'ready');});
test('deleting queued artwork never spends a provider call and preserves budget ledger',async()=>{const f=await fixture(),c=await login(f);const {job}=await (await makeJob(f,c)).json();assert.equal((await request(f,'/jobs/'+job.id,'DELETE',null,c)).status,200);await f.service.alarm();assert.equal((await request(f,'/jobs/'+job.id,'GET',null,c)).status,404);assert.equal(await f.store.get('total-attempts'),1);});
test('deleted visual edition requires an explicit new edition',async()=>{const f=await fixture(),c=await login(f);const {job}=await (await makeJob(f,c)).json();await request(f,'/jobs/'+job.id,'DELETE',null,c);assert.equal((await makeJob(f,c)).status,409);assert.equal((await makeJob(f,c,{...spec,edition:1})).status,202);assert.equal(await f.store.get('total-attempts'),2);});
test('deletion during provider generation prevents retention of the result',async t=>{const f=await fixture(),c=await login(f);const {job}=await (await makeJob(f,c)).json();let release,started;const begin=new Promise(r=>started=r);const old=globalThis.fetch;globalThis.fetch=async()=>{started();return await new Promise(r=>release=()=>r(Response.json(image())));};t.after(()=>globalThis.fetch=old);const alarm=f.service.alarm();await begin;assert.equal((await request(f,'/jobs/'+job.id,'DELETE',null,c)).status,202);release();await alarm;assert.equal(f.bucket.map.size,0);assert.equal((await request(f,'/jobs/'+job.id,'GET',null,c)).status,404);});

test('a queued deletion cannot race into a provider call while object deletion waits',async t=>{
 const f=await fixture(),c=await login(f);const {job}=await(await makeJob(f,c)).json();
 let release,start;const began=new Promise(r=>start=r);f.bucket.delete=async()=>{start();await new Promise(r=>release=r);};
 const old=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return Response.json(image());};t.after(()=>globalThis.fetch=old);
 const deleting=request(f,'/jobs/'+job.id,'DELETE',null,c);await began;
 const state=await f.store.get('job:'+f.a+':'+job.id);
 assert.ok(state.deleteRequested||state.status==='deleted'||state.status==='deleting','deletion intent must precede object-storage I/O');
 release();await deleting;await f.service.alarm();assert.equal(calls,0);assert.equal(f.bucket.map.size,0);
});
test('the provider request uses non-following redirects compatible with Workers',async()=>{
 await generateXaiPortrait(spec,{apiKey:'fixture',fetchImpl:async(_url,options)=>{assert.equal(options.redirect,'manual');return Response.json(image());}});
});
