import NeuroheroFieldGuide,{HeroStrengthsCard} from './neurohero/NeuroheroFieldGuide';
import {JourneyRail} from './CortexExperience';
import {buildHeroProfile} from '../utils/neurohero/engine.mjs';
import {HeroSignature,HeroAuditBody} from './neurohero/NeuroheroReportBlocks';
import CortexBrand from './CortexBrand';
import DevelopmentResearch from './DevelopmentResearch';
import {PersonContextSummary,DevelopmentEventSummary} from './DevelopmentContext';
import {DEVELOPMENT_VERSION,CONTEXT_VERSION} from '../data/developmentContext.mjs';
import React,{useMemo,useState,useRef,useEffect} from 'react';
import {buildInsights,REPORT_VERSION} from '../utils/insightProfile.mjs';
import {INSIGHT_QUESTIONS,INSIGHT_CHOICES} from '../data/insightQuestions.mjs';
import {REGIONS,ANATOMY_SOURCES} from '../data/anatomyCatalog.mjs';
import {REGION_STUDIES} from '../data/regionStudies.mjs';
import {StudyCard} from './ResearchStudies';
import {ALL_QUESTIONS} from '../data/assessmentQuestions.mjs';
import {researchForQuestion} from '../data/questionRegionLinks.mjs';
import {SOURCES} from '../data/assessmentEvidence.mjs';
// Report styles are loaded after legacy styles by main.jsx.

const label=value=>INSIGHT_CHOICES.find(([id])=>id===value)?.[1]||'Not reviewed';
const sourceURL=s=>s?.url||s?.href;
function Mark(){return <div className="cc-paper-brand"><CortexBrand variant="paper"/></div>;}
function Plate({view='deep',caption,large=false}){const [failed,setFailed]=useState(false);return <figure className={`cc-atlas-plate ${large?'large':''}`}>{!failed?<img src={`/reports/brain-${view}.jpg`} width="680" height="430" alt={`${caption}. Generic Blender teaching anatomy, not your brain.`} onError={()=>setFailed(true)}/>:<div className="cc-plate-fallback">◇<span>Generic teaching anatomy<br/>The text atlas below remains available.</span></div>}<figcaption>{caption} <span>Generic model · not a scan</span></figcaption></figure>;}
function Page({children,className=''}){return <section className={`cc-paper-page ${className}`}>{children}</section>;}
function SectionTitle({number,eyebrow,title,children}){return <header className="cc-paper-section"><span className="cc-paper-number">{number}</span><div><span className="cc-eyebrow">{eyebrow}</span><h2>{title}</h2>{children&&<p>{children}</p>}</div></header>;}
function TraitCard({item,compact=false}){return <article className={`cc-power-card ${item.kind==='friction'?'friction':''}`} data-report-trait={item.id}><div className="cc-power-top"><span>{item.kind==='friction'?'↘':'✦'}</span><small>{label(item.response)} · self-reported</small></div><h3>{item.title}</h3><p>{item.property}.</p>{!compact&&item.use&&<p>{item.use}</p>}{!compact&&<p className="cc-card-action"><b>Try noticing:</b> {item.try}</p>}</article>;}
function Combo({item,compact=false}){return <article className="cc-combination" data-combination={item.id}><span className="cc-evidence-tag hypothesis">UNTESTED COMBINATION HYPOTHESIS</span><h3>{item.name}</h3><p className="cc-combo-formula">{item.basis.map(b=>`${b.title} (${label(b.response)})`).join(' + ')}</p><p>{item.possible}</p><p className="cc-combo-cost"><b>Possible kryptonite:</b> {item.cost}</p>{!compact&&<><p><b>Context:</b> {item.context}</p><p><b>Reality check:</b> {item.check}</p><p><b>Reported friction:</b> {item.reportedFrictions.length?item.reportedFrictions.map(q=>q.title).join(', '):'No matched difficulty was endorsed. That does not establish its absence.'}</p><p><b>Reported support:</b> {item.reportedResources.length?item.reportedResources.map(q=>q.title).join(', '):'No matched present-day support was endorsed; availability is unknown.'}</p><p className="cc-small-note">{item.evidence} Neither component nor their combination establishes any anatomical change.</p></>}</article>;}
function Empty({children}){return <p className="cc-report-empty">{children}</p>;}
function SupportSummary({profile,insights}){return <div className="cc-support-pair"><div><h3>What helped earlier</h3>{profile.supports.length?<ul>{profile.supports.map(s=><li key={s.id}>{s.title}</li>)}</ul>:<p>No childhood support was explicitly endorsed. Missing is not absent.</p>}</div><div><h3>What helps now</h3>{insights.resources.length?<ul>{insights.resources.map(s=><li key={s.id}>{s.title} · {label(s.response)}</li>)}</ul>:<p>Present-day supports have not been endorsed. Their availability remains unknown.</p>}</div></div>;}
function Footer({demo,kind}){return <footer className="cc-paper-foot"><b>◇ Cortex Compass / {kind}</b><span>{demo?'FICTIONAL SAMPLE · ':''}Educational reflection, not a diagnosis, brain scan or tested ability.</span><span>{REPORT_VERSION}</span></footer>;}

function SuperheroReport({profile,insights,demo,heroProfile,portraitChoices,portraitAsset,insightAnswers}){if(heroProfile?.signature)return <NeuroheroFieldGuide heroProfile={heroProfile} portraitChoices={portraitChoices} portraitAsset={portraitAsset} insightAnswers={insightAnswers} demo={demo}/>;return <div data-report="superhero">
 <Page className="cc-super-cover"><Mark/>{demo&&<p className="cc-fictional">FICTIONAL SAMPLE · NOT YOUR RESULTS</p>}<div className="cc-super-hero"><div><span className="cc-eyebrow">A FIELD GUIDE, NOT A FIXED IDENTITY</span><h1>Superhero<br/><em>Report</em></h1><p className="cc-paper-deck">Possible strengths.<br/>Real-world friction.<br/>Room to be different.</p></div><Plate view="deep" caption="Systems working together" large/></div>
 <p className="cc-report-boundary">“Superpowers” and “kryptonites” are metaphors. Cards below come only from your present-day answers, not presumed brain deformations or a history of adversity.</p>

 <SectionTitle number="01" eyebrow="WHAT YOU RECOGNIZE" title="Your possible superpowers"/>
 <div className="cc-power-grid">{insights.strengths.length?insights.strengths.slice(0,3).map(q=><TraitCard key={q.id} item={q} compact/>):<Empty>No strengths have been endorsed yet. That does not mean you have none. Add your present-day observations to personalize this section.</Empty>}</div>
 <SectionTitle number="02" eyebrow="WHAT CAN BE DEMANDING" title="Your possible kryptonites"/>
 <div className="cc-power-grid">{insights.frictions.length?insights.frictions.slice(0,3).map(q=><TraitCard key={q.id} item={q} compact/>):<Empty>No present-day difficulty was endorsed. We do not invent a downside from a strength or infer one from your history.</Empty>}</div>
 <p className="cc-small-note">Up to three of each are shown in fixed questionnaire order, not a ranking. The Scientific Report contains the complete observation record.</p><Footer demo={demo} kind="Superhero Report"/>
 </Page>
 <Page><Mark/><SectionTitle number="03" eyebrow="WHEN PATTERNS MEET" title="Possible combination powers">A combination may be useful in one setting and demanding in another. These named combinations are ideas to test—not validated traits or measured neural synergies.</SectionTitle>
 <div className="cc-combo-grid">{insights.combinations.length?insights.combinations.slice(0,2).map(c=><Combo key={c.id} item={c} compact/>):<Empty>No combination was selected. Both component strengths must be explicitly endorsed; unanswered items cannot complete a combination.</Empty>}</div>
 <SectionTitle number="04" eyebrow="PROTECTIVE FACTORS & CURRENT RESOURCES" title="Your support kit"/>
 <SupportSummary profile={profile} insights={insights}/><p className="cc-small-note">Supports may matter, but this reflection cannot quantify their effect or subtract them from earlier experiences.</p>
 <div className="cc-next-experiment"><span className="cc-eyebrow">ONE SMALL REALITY CHECK</span><h3>Try it. Notice it. Revise the story.</h3><p>{insights.strengths[0]?.try||'Choose one situation where you felt capable and one where you needed support. Look for the conditions that differed.'}</p><p>Keep track of when the description does <b>not</b> fit, too. There is no obligation to turn a painful experience into a positive story.</p></div>
 <p className="cc-report-boundary">Your brain’s maturation, structure and activation were not measured. Developmental stage, sex and gender do not assign your powers. The Scientific Report explains the specific research, including stimulus-dependent differences and its limits.</p><Footer demo={demo} kind="Superhero Report"/>
 </Page></div>;}

function ScientificReport({profile,insights,answers,demo,privateHistory,privateContext,personContext,heroProfile}){
 const studies=Object.entries(REGION_STUDIES),used=new Set(profile.studyLinks.map(s=>s.id));
 return <div data-report="scientific"><Page className="cc-science-cover"><Mark/>{demo&&<p className="cc-fictional">FICTIONAL SAMPLE · NOT YOUR RESULTS</p>}<span className="cc-eyebrow">METHODS · ANATOMY · EVIDENCE · LIMITATIONS</span><h1>Scientific<br/><em>Report</em></h1><p className="cc-paper-deck">An auditable explanation of the research guide and your reflection—not a scientific assessment of your individual brain.</p><Plate view="cutaway" caption="Medial cutaway / schematic internal structures" large/>
 <div className="cc-report-metrics"><div><strong>{REGIONS.length}</strong><span>Teaching regions</span></div><div><strong>{studies.length}</strong><span>Core region studies</span></div><div><strong>{insights.answered}/{insights.total}</strong><span>Present-day responses</span></div></div>
 <div className="cc-evidence-lanes"><article><span className="cc-evidence-tag">OBSERVATION</span><p>What you directly reported. Not independently verified or objectively tested.</p></article><article><span className="cc-evidence-tag research">RESEARCH</span><p>What a cited study measured in its participants, with design and limits preserved.</p></article><article><span className="cc-evidence-tag hypothesis">HYPOTHESIS</span><p>Editorial combinations to consider. No calibrated confidence or established neural mechanism.</p></article><article><span className="cc-evidence-tag unknown">UNKNOWN</span><p>Your brain anatomy, causation, unreported traits, clinical status and actual synergy.</p></article></div>
 <p className="cc-report-boundary">Correlation is not causation. A group association does not establish an individual effect. More or less volume, thickness, activity or connectivity is not a general scale of better or worse.</p><Footer demo={demo} kind="Scientific Report"/></Page>
 <Page><Mark/><SectionTitle number="01" eyebrow="TRANSPARENT ARCHITECTURE" title="How this report was assembled"/>
 <ol className="cc-method-steps"><li><b>Preserve observations.</b> History, reported developmental stage, response and support at the time are separate observations. Optional calendar ages never determine maturation. Prenatal context remains separate.</li><li><b>Select research reading.</b> Endorsed history questions select existing question-to-study links. A domain match is different from related evidence; unmapped answers stay unmapped.</li><li><b>Describe present-day patterns.</b> Only “Often” or “Sometimes” on a separate current observation selects a strength, friction or resource card. This is an editorial inclusion rule, not a validated cutoff.</li><li><b>Suggest combinations.</b> Both listed strength observations must be endorsed. The output is an untested hypothesis. No study-derived interaction coefficient, risk estimate or neural parameter is computed.</li><li><b>Render the same model.</b> Every reader sees the same generic teaching anatomy. Colors and separated pieces identify structures, not individual injury or activation.</li></ol>
 <h3>Extrapolation stops before anatomy</h3><p>“You reported noticing details” → “Signal scout is a possible shorthand” is a transparent editorial description. Adding “you also reported generating ideas” permits a possible combination to explore. It does <b>not</b> permit “therefore your amygdala is enlarged,” “your brain has a deformation,” or “you have a superior ability.” Adding the word “may” would not supply the missing evidence.</p>
 <h3>What could explain a similar answer?</h3><p>Practice, personal interests, current circumstances, sleep, task demands, social support, reporting differences and many other influences can produce similar observations. The tool does not distinguish those explanations or establish that childhood events caused a present-day pattern.</p>
 <h3>What would stronger evidence require?</h3><p>A prespecified construct and outcome, suitable validated measurements, an appropriate comparison, assessment of alternative explanations, independent replication and tests of generalization. A claimed neural mechanism would need relevant brain data; a casual questionnaire cannot substitute for that.</p>
 <p className="cc-source-note">Methods context: Marek et al. (2022), <i>Reproducible brain-wide association studies require thousands of individuals</i>. DOI: <a href="https://doi.org/10.1038/s41586-022-04492-9" target="_blank" rel="noreferrer">10.1038/s41586-022-04492-9</a>. Brain-wide association reproducibility is design-dependent; this does not mean all imaging studies need the same sample size. Publisher correction: 10.1038/s41586-022-04692-3.</p>
 <div className="cc-report-boundary"><b>Product validation status:</b> The reflection and named combinations are not clinically validated instruments. The research library is curated, not a systematic review of all literature. The teaching model has not received an independent neuroanatomical expert review.</div>
 <Footer demo={demo} kind="Scientific Report"/></Page>
 <Page className="cc-development-paper"><Mark/><DevelopmentResearch full/><Footer demo={demo} kind="Scientific Report"/></Page>
 <Page><Mark/><SectionTitle number="02" eyebrow="INPUTS, NOT DIAGNOSES" title="Your observation ledger">Every current response is shown, including the unknowns. A skipped or unreviewed question is not a negative answer.</SectionTitle>
 <table className="cc-observation-table"><thead><tr><th scope="col">Observation</th><th scope="col">Type</th><th scope="col">Your response</th></tr></thead><tbody>{INSIGHT_QUESTIONS.map(q=><tr key={q.id}><th scope="row">{q.title}</th><td>{q.kind==='resource'?'Current resource':q.kind}</td><td>{label(insights.answers[q.id])}</td></tr>)}</tbody></table>
 <p>{insights.unknown.length} present-day observations remain unknown (not reviewed, not sure, or skipped). Rarely / not now is a time-specific response, not proof that a capacity is absent.</p>
 <SupportSummary profile={profile} insights={insights}/><p className="cc-small-note">Childhood and current supports are not treated as interchangeable, and no numerical protective effect is estimated.</p>
 <p className="cc-report-boundary">Privacy: {privateHistory?'You chose to include your sensitive history appendix in this report.':'Adversity and prenatal responses, including developmental context and calendar ages, are excluded by default. Reported childhood supports are included. Enabling the private appendix is a separate choice.'} Present-day observations and past/current support information are still sensitive. Share thoughtfully.</p><Footer demo={demo} kind="Scientific Report"/></Page>
 <Page><Mark/><SectionTitle number="03" eyebrow="CONTEXTUAL INTERPRETATION" title="Possible strengths and friction"/><div className="cc-power-grid detailed">{insights.strengths.map(q=><TraitCard key={q.id} item={q}/>)}{insights.frictions.map(q=><TraitCard key={q.id} item={q}/>)}{!insights.strengths.length&&!insights.frictions.length&&<Empty>No present-day strength or friction card was selected. No anatomy-based replacement is generated.</Empty>}</div><Footer demo={demo} kind="Scientific Report"/></Page>
 <Page className="cc-combination-section"><Mark/><SectionTitle number="04" eyebrow="COMBINATIONS, MODERATION & UNCERTAINTY" title="When more than one pattern is present"/>
 <p>Co-occurrence means two things are reported together. Synergy requires evidence that their combined effect differs from the appropriate comparison or additive expectation on a specified outcome and scale. Co-occurrence alone does not demonstrate synergy.</p><p>The following combinations come only from current strength observations. Their possible benefits and costs are editorial hypotheses. No causal or anatomical claim follows.</p>
 <div className="cc-combo-grid">{insights.combinations.length?insights.combinations.map(c=><Combo key={c.id} item={c}/>):<Empty>No named combination meets the two-observation inclusion rule.</Empty>}</div>
 <Footer demo={demo} kind="Scientific Report"/></Page>
 {Object.keys(heroProfile?.answers||{}).length>0&&<Page><Mark/><SectionTitle number="03B" eyebrow="DEEP HERO ATLAS" title="From observations to a candidate composition">Counterexamples can remove a component from a hero signature. History never fills in an unanswered functional process.</SectionTitle><HeroAuditBody heroProfile={heroProfile}/><Footer demo={demo} kind="Scientific Report"/></Page>}
 <Page><Mark/><SectionTitle number="04B" eyebrow="WHAT COMBINATION RESEARCH CAN SUPPORT" title="Interactions and protective factors"/>
 <h3>Direct combined-exposure research is a different category</h3><p>The registry includes Puetz et al., comparing abuse-only, neglect-only, combined and comparison groups on a threat-processing task. Its group findings were not a simple sum of separate patterns. That result does not validate a “meta-power,” prove a brain deformation, or let this app predict an individual response.</p><p>See the complete Puetz study card in the primary-study library below. It is shown for every reader as methods context, not because we have assigned you to an exposure group.</p>
 <h3>Protective factors: possible modifiers, not a subtraction</h3><p>Caregiving, relationships and current resources are separate observations. Whether a particular factor modifies a particular association depends on the population, timing, design and outcome. The Luby caregiving study and Bick foster-care trial below offer different kinds of evidence; neither supplies a universal buffering percentage for these answers.</p><p><b>Unknown here:</b> whether a combination changes your performance, whether supports modify that effect, its direction or magnitude, and any underlying neural mechanism.</p><Footer demo={demo} kind="Scientific Report"/></Page>
 <Page><Mark/><SectionTitle number="05" eyebrow="A SHARED EDUCATIONAL MODEL" title="The brain, separated into readable systems">Locations and functions are broad teaching summaries. A region participates in multiple networks; it is not a standalone “power center.”</SectionTitle>
 <div className="cc-atlas-grid"><Plate view="surface" caption="Left lateral cortical surface"/><Plate view="right" caption="Right lateral cortical surface"/><Plate view="cutaway" caption="Medial cutaway"/><Plate view="deep" caption="Separated hemispheres and internal guides"/></div>
 <p className="cc-report-boundary">The model has 26 selectable teaching topics and 47 meshes. Cortical partitions have geometric, not atlas-registered boundaries. Internal structures are schematic. These are not personal scans, measured changes, injuries, or segmented research clusters.</p>
 <p className="cc-small-note">Artwork adapted in Blender from “Brain - with labeled parts” by AbdulMuhaymin, CC BY 4.0. Original: sketchfab.com/3d-models/brain-with-labeled-parts-28c8971e11334e8b97a2a0d6235992e8. Geometric teaching partitions and schematic guides were added. Original authors are not represented as endorsing this tool.</p>
 <div className="cc-region-atlas">{REGIONS.map(r=>{const links=studies.filter(([,s])=>s.regions.some(v=>v.id===r.id));return <article key={r.id} data-atlas-region={r.id} style={{'--region-color':r.color}}><h3><i/>{r.name}</h3><p><b>Where:</b> {r.where}</p><p><b>Role:</b> {r.function}</p><p><b>Studied associations:</b> {links.length?links.map(([id,s])=>`${s.label} (${s.measure})`).join('; '):'No specific adversity study is assigned in this curated registry. This is not evidence that no research exists.'}</p><p className="cc-small-note">{r.look}</p><a href={ANATOMY_SOURCES[r.source]?.url} target="_blank" rel="noreferrer">Anatomy source: {ANATOMY_SOURCES[r.source]?.label}</a></article>;})}</div>
<Footer demo={demo} kind="Scientific Report"/></Page>
 <Page><Mark/><SectionTitle number="06" eyebrow="FULL CURATED PRIMARY-STUDY REGISTRY" title="What the studies actually found">All {studies.length} registry entries are included so the library does not reveal which history answers you selected. Each entry keeps the measurement, population, finding and limitation together. This is not an exhaustive literature review.</SectionTitle>
 <div className="cc-scientific-studies">{studies.map(([id])=><StudyCard key={id} id={id}/>)}</div><Footer demo={demo} kind="Scientific Report"/></Page>
 <Page><Mark/><SectionTitle number="07" eyebrow="COVERAGE & ASSUMPTIONS" title="Question-to-research audit">These are all questionnaire domains—not your answers. Domain and related describe exposure fit, not a clinical certainty grade. Missing mappings remain visible.</SectionTitle>
 <div className="cc-question-audit-print">{ALL_QUESTIONS.map(q=>{const r=researchForQuestion(q.id);return <article key={q.id}><h3>{q.title} <span>{r.status}</span></h3><p>{r.note}</p><p>{r.studies.length?`Linked primary studies: ${r.studies.map(id=>REGION_STUDIES[id]?.label).join('; ')}`:'No region assignment in the current review.'}</p></article>;})}</div>
 <h3>Questionnaire and context sources</h3><div className="cc-domain-sources">{Object.entries(SOURCES).filter(([id])=>!REGION_STUDIES[id]).map(([id,s])=><p key={id}><b>{s.label||s.title||id}</b>{sourceURL(s)&&<> · <a href={sourceURL(s)} target="_blank" rel="noreferrer">{sourceURL(s)}</a></>}</p>)}</div>
 <h3>Interpretation checklist</h3><p>Do not convert task activity into tissue volume, connectivity into damage, a retrospective age range into a sensitive-period multiplier, or a supportive relationship into a percentage reduction. Study populations differ; shared cohorts do not automatically provide independent replication. Null and conflicting findings are retained. Current self-report is not proof of objectively superior ability.</p><p><b>Versions:</b> {profile.version} · {profile.evidenceVersion} · {insights.version} · {REPORT_VERSION} · {DEVELOPMENT_VERSION} · {CONTEXT_VERSION}. Rule order is deterministic. Text and interpretation are deterministic; no cloud scoring is used. Any chosen artwork is separate from the evidence.</p><Footer demo={demo} kind="Scientific Report"/></Page>
 {privateHistory&&<Page><Mark/><SectionTitle number="08" eyebrow="EXPLICITLY INCLUDED · SENSITIVE" title="Private history appendix"/><p>{profile.answered} of {profile.total} history/support prompts responded to; {profile.unsure} uncertain, {profile.skipped} skipped, {profile.unanswered} not reviewed. The counts are not severity or ACE scores.</p><div className="cc-private-ledger">{ALL_QUESTIONS.map(q=><p key={q.id}><b>{q.title}:</b> {answers[q.id]?.value||'Not reviewed'}</p>)}</div>{profile.timeline.map(row=><article className="cc-history-row" key={row.id}><h3>{row.title}</h3>{row.kind==='history'&&<DevelopmentEventSummary value={row.development}/>}<p>Calendar history: {row.timingText} · Information source: {row.source} · Frequency: {row.frequency}</p></article>)}<h3>Reading links selected by these answers</h3><p>{used.size?[...used].map(id=>REGION_STUDIES[id]?.label).join('; '):'No primary-study link selected.'}</p><p>These are reading selections, not affected-region or personal-risk findings.</p><Footer demo={demo} kind="Scientific Report"/></Page>}
 {privateContext&&<Page><Mark/><SectionTitle number="09" eyebrow="EXPLICITLY INCLUDED · SENSITIVE" title="Private sex and gender context"/><PersonContextSummary value={personContext}/><p>Current identity is not historical identity. No hormones, brain maturity or response probabilities were inferred. All source-study comparisons remain visible to every reader.</p><Footer demo={demo} kind="Scientific Report"/></Page>}
 </div>;
}

export default function CompassReports({profile,insightAnswers,heroAnswers={},selectedHeroId='',onHeroEdit,portraitChoices={},portraitAsset=null,answers,demo,onBack,onEdit,personContext={}}){
 const [privateContext,setPrivateContext]=useState(false);
 const [kind,setKind]=useState('superhero'),[privateHistory,setPrivateHistory]=useState(false),[printing,setPrinting]=useState(false),[notice,setNotice]=useState('');
 const busy=useRef(false),insights=useMemo(()=>buildInsights(insightAnswers),[insightAnswers]),heroProfile=useMemo(()=>buildHeroProfile(heroAnswers,selectedHeroId),[heroAnswers,selectedHeroId]);
 const [printReady,setPrintReady]=useState(false);
 useEffect(()=>{
  let cancelled=false;setPrintReady(false);
  const oldTitle=document.title;
  document.title=`Cortex Compass - ${kind==='superhero'?'Superhero Report':kind==='hero-card'?'Strengths-only card':'Scientific Report'}${demo?' - Fictional sample':''}`;
  let preparing=false;
  const prepare=async()=>{if(cancelled||preparing||document.querySelector('.cc-report-document [data-portrait-state="loading"]'))return;preparing=true;await Promise.all([...document.querySelectorAll('.cc-report-document img')].map(img=>img.decode?.().catch(()=>{})));if(document.fonts?.ready)await document.fonts.ready;if(!cancelled){setPrintReady(true);clearInterval(timer);}};
  const timer=setInterval(prepare,100);
  return()=>{cancelled=true;clearInterval(timer);document.title=oldTitle;};
 },[kind,demo,portraitAsset?.id]);
 // Keep the native print invocation synchronous with the user's tap.
 const print=()=>{if(busy.current||!printReady)return;busy.current=true;setPrinting(true);setNotice('');try{
  window.print();
 }catch{setNotice('The print dialog could not open. Use your browser’s Print or Share menu.');}finally{busy.current=false;setPrinting(false);}};
 return <main className={`cc-shell cc-reports-screen cc-report-${kind}`}><header className="cc-nav cc-print-hide"><div className="cc-brand"><CortexBrand/></div><button className="cc-secondary" disabled={printing} onClick={onBack}>Back to overview</button></header>
 <section className="cc-report-tools cc-print-hide"><JourneyRail active="reports"/><div><span className="cc-eyebrow">TWO REPORTS · ONE HONEST REFLECTION</span><h2>Choose your report</h2><p>Superhero: a two-page field guide. Scientific: the complete curated research and method.</p></div><div className="cc-report-switch" role="group" aria-label="Report type">{[['superhero','Superhero Report'],['scientific','Scientific Report'],...(heroProfile.signature?[['hero-card','Strengths-only card']]:[])].map(([id,text])=><button key={id} disabled={printing} aria-pressed={kind===id} onClick={()=>{setKind(id);window.scrollTo({top:0});}}>{text}</button>)}</div>
 <div className="cc-report-tool-actions">{onHeroEdit&&<button className="cc-secondary" onClick={onHeroEdit}>Deep Hero Atlas</button>}<button className="cc-secondary" disabled={printing} onClick={onEdit}>Edit strengths & friction</button><button className="cc-primary" disabled={printing||!printReady} onClick={print}>{printing||!printReady?'Preparing report…':`Print ${kind==='superhero'?'Superhero':kind==='hero-card'?'Strengths card':'Scientific'} / Save PDF`}</button></div>
 {kind==='scientific'&&<label className="cc-private-choice"><input type="checkbox" disabled={printing} checked={privateHistory} onChange={e=>setPrivateHistory(e.target.checked)}/><span>Also include my adversity/prenatal responses, developmental context and calendar ages in a private appendix. Reported supports are already included. <b>Off by default.</b></span></label>}
 {kind==='scientific'&&<label className="cc-private-context-choice cc-private-choice"><input type="checkbox" disabled={printing} checked={privateContext} onChange={e=>setPrivateContext(e.target.checked)}/><span>Also include my sex, gender and hormonal-context answers in a separate sensitive appendix. <b>Off by default.</b></span></label>}
 <p className="cc-small-note">On iPhone or iPad, the browser’s Share → Print or Save to Files options may be available. PDF export is handled by your browser; nothing is uploaded.</p>{notice&&<p role="status">{notice}</p>}
 </section><div className="cc-report-document">{kind==='hero-card'?<HeroStrengthsCard heroProfile={heroProfile} portraitChoices={portraitChoices} portraitAsset={portraitAsset} demo={demo}/>:kind==='superhero'?<SuperheroReport profile={profile} insights={insights} insightAnswers={insightAnswers} demo={demo} heroProfile={heroProfile} portraitChoices={portraitChoices} portraitAsset={portraitAsset}/>:<ScientificReport profile={profile} insights={insights} answers={answers} demo={demo} privateHistory={privateHistory} privateContext={privateContext} personContext={personContext} heroProfile={heroProfile}/>}</div><div className="cc-print-running-foot" aria-hidden="true"><b>◇ Cortex Compass / {kind==='superhero'?'Superhero Report':kind==='hero-card'?'Strengths-only card':'Scientific Report'}</b><span>{demo?'FICTIONAL SAMPLE · ':''}Educational reflection · {REPORT_VERSION}</span></div></main>;
}
