import React,{useMemo,useState} from 'react';
import CortexBrain from './CortexBrain';
import {AGE_BANDS,FREQUENCIES,SECTIONS,calculateProfile,SUPERPOWERS,KRYPTONITES} from '../data/cortexCompass';

const freqLabel={once:'Once',sometimes:'Sometimes',often:'Often',chronic:'Long-term / chronic'};
const seedDemo={unsafe_home:{value:'yes',ages:['3-5','6-11'],frequency:'often'},emotional_neglect:{value:'yes',ages:['3-5','11-13'],frequency:'chronic'},bullying:{value:'yes',ages:['11-13'],frequency:'often'},safe_adult:{value:'yes'},competence:{value:'yes'},close_friend:{value:'yes'}};
const labelBand=b=>({low:'Lower',moderate:'Moderate',elevated:'Elevated',high:'Higher'})[b]||b;

export default function CortexCompass(){
 const [screen,setScreen]=useState('welcome'); const [sectionIndex,setSectionIndex]=useState(0); const [answers,setAnswers]=useState({}); const [selectedRegion,setSelectedRegion]=useState(null); const [saved,setSaved]=useState(false);
 const profile=useMemo(()=>calculateProfile(answers),[answers]); const section=SECTIONS[sectionIndex];
 const setValue=(id,value)=>setAnswers(a=>({...a,[id]:{...(a[id]||{}),value}}));
 const toggleAge=(id,age)=>setAnswers(a=>{const prev=a[id]||{value:'yes'};const ages=prev.ages||[];return {...a,[id]:{...prev,ages:ages.includes(age)?ages.filter(x=>x!==age):[...ages,age]}}});
 const setFrequency=(id,frequency)=>setAnswers(a=>({...a,[id]:{...(a[id]||{value:'yes'}),frequency}}));
 const answeredInSection=section?.questions.filter(q=>answers[q.id]?.value).length||0;
 const saveProfile=()=>{localStorage.setItem('cortex-compass-profile',JSON.stringify({answers,profile,savedAt:new Date().toISOString()}));setSaved(true);};
 const resume=()=>{try{const x=JSON.parse(localStorage.getItem('cortex-compass-profile'));if(x?.answers){setAnswers(x.answers);setScreen('results');}}catch{}}
 const start=()=>{setAnswers({});setSectionIndex(0);setScreen('assessment');};
 const next=()=>{if(sectionIndex<SECTIONS.length-1)setSectionIndex(i=>i+1);else setScreen('results');window.scrollTo({top:0,behavior:'smooth'});};
 const topRegions=profile.regions.slice(0,5); const hasSaved=typeof localStorage!=='undefined'&&localStorage.getItem('cortex-compass-profile');
 if(screen==='welcome') return <main className="cc-shell cc-welcome">
   <header className="cc-nav"><div className="cc-brand"><span className="cc-mark">◇</span><div><b>Cortex Compass</b><small>by Utlyze</small></div></div><span className="cc-chip">Educational • reflective • non-diagnostic</span></header>
   <section className="cc-hero"><div className="cc-hero-copy"><span className="cc-eyebrow">RESEARCH-INFORMED SELF REFLECTION</span><h1>Understand the patterns.<br/><em>See the systems.</em></h1><p>A compassionate, visual way to explore how early experiences may relate to stress, memory, regulation, and adaptation—without pretending a questionnaire is a brain scan.</p><div className="cc-actions"><button className="cc-primary" onClick={start}>Begin my reflection <span>→</span></button><button className="cc-secondary" onClick={()=>{setAnswers(seedDemo);setScreen('results')}}>Explore sample profile</button>{hasSaved&&<button className="cc-secondary" onClick={resume}>Open saved profile</button>}</div><div className="cc-trust"><span>25 optional prompts</span><span>5 simple sections</span><span>Private device save</span></div></div><div className="cc-hero-brain"><CortexBrain profile={calculateProfile(seedDemo)} compact/><div className="cc-floating one"><b>43 → 10</b><span>brain regions grouped into understandable systems</span></div><div className="cc-floating two"><b>Deterministic</b><span>same answers, same result</span></div></div></section>
   <section className="cc-flow"><span>Reflect</span><i>→</i><span>Answer</span><i>→</i><span>Map</span><i>→</i><span>Understand</span><i>→</i><span>Build</span></section>
   <footer className="cc-note">Cortex Compass shows research-informed associations at a population level. It does not determine what happened to an individual brain and is not medical advice.</footer>
 </main>;
 if(screen==='assessment') return <main className="cc-shell cc-assessment">
   <header className="cc-nav"><button className="cc-brand button" onClick={()=>setScreen('welcome')}><span className="cc-mark">◇</span><div><b>Cortex Compass</b><small>Reflection</small></div></button><div className="cc-progress-meta"><span>Section {sectionIndex+1} of {SECTIONS.length}</span><strong>{Math.round(((sectionIndex+(answeredInSection/section.questions.length))/SECTIONS.length)*100)}%</strong></div></header>
   <div className="cc-progress"><i style={{width:`${((sectionIndex+(answeredInSection/section.questions.length))/SECTIONS.length)*100}%`}}/></div>
   <section className="cc-assessment-wrap"><aside><span className="cc-eyebrow">YOUR REFLECTION</span><h2>{section.icon} {section.title}</h2><p>{section.subtitle}</p><nav>{SECTIONS.map((s,i)=><button key={s.id} className={i===sectionIndex?'active':i<sectionIndex?'done':''} onClick={()=>setSectionIndex(i)}><i>{i<sectionIndex?'✓':i+1}</i><span>{s.title}</span></button>)}</nav><div className="cc-safety"><b>You control the pace.</b><span>Every question is optional. “Prefer not to answer” is a complete answer.</span></div></aside>
   <div className="cc-question-list">{section.questions.map((q,idx)=>{const a=answers[q.id]||{};return <article key={q.id} className={`cc-question ${a.value?'answered':''}`}><div className="cc-qhead"><span>{String(idx+1).padStart(2,'0')}</span><h3>{q.text}</h3></div><div className="cc-choice"><button className={a.value==='yes'?'selected':''} onClick={()=>setValue(q.id,'yes')}>Yes</button><button className={a.value==='no'?'selected':''} onClick={()=>setValue(q.id,'no')}>No</button><button className={a.value==='skip'?'selected':''} onClick={()=>setValue(q.id,'skip')}>Prefer not to answer</button></div>{a.value==='yes'&&!q.protective&&<div className="cc-follow"><label>When? <small>Select any that apply</small></label><div className="cc-pills">{AGE_BANDS.map(x=><button key={x} className={(a.ages||[]).includes(x)?'selected':''} onClick={()=>toggleAge(q.id,x)}>{x}</button>)}</div><label>How persistent was it?</label><div className="cc-pills">{FREQUENCIES.map(x=><button key={x} className={a.frequency===x?'selected':''} onClick={()=>setFrequency(q.id,x)}>{freqLabel[x]}</button>)}</div></div>}</article>})}
   <div className="cc-section-actions"><button className="cc-secondary" disabled={sectionIndex===0} onClick={()=>setSectionIndex(i=>Math.max(0,i-1))}>← Previous</button><button className="cc-primary" onClick={next}>{sectionIndex===SECTIONS.length-1?'Build my map':'Continue'} <span>→</span></button></div></div></section>
 </main>;
 return <main className="cc-shell cc-results">
   <header className="cc-nav cc-print-hide"><button className="cc-brand button" onClick={()=>setScreen('welcome')}><span className="cc-mark">◇</span><div><b>Cortex Compass</b><small>Personal brain insight report</small></div></button><div className="cc-actions small"><button className="cc-secondary" onClick={()=>setScreen('assessment')}>Edit answers</button><button className="cc-secondary" onClick={saveProfile}>{saved?'Saved ✓':'Save profile'}</button><button className="cc-primary" onClick={()=>window.print()}>Print / PDF</button></div></header>
   <section className="cc-report-head"><div><span className="cc-eyebrow">YOUR CORTEX COMPASS</span><h1>Patterns, not predictions.</h1><p>This report converts your answers into a consistent educational map of systems worth understanding and supporting.</p></div><div className={`cc-load ${profile.band}`}><small>Overall mapping load</small><strong>{labelBand(profile.band)}</strong><span>{Math.round(profile.buffer*100)}% protective buffering reflected</span></div></section>
   <section className="cc-summary-grid"><div><small>Primary themes</small><strong>{profile.strongest.join(' • ')||'No major adversity themes endorsed'}</strong></div><div><small>Sensitive windows reported</small><strong>{profile.windows.join(' • ')||'No timing pattern available'}</strong></div><div><small>Protective factors</small><strong>{profile.protective>3?'Strong':'Present'} buffering signals</strong></div><div><small>Model version</small><strong>{profile.version}</strong></div></section>
   <section className="cc-map-grid"><div className="cc-map-card"><div className="cc-card-title"><div><span className="cc-eyebrow">INTERACTIVE MAP</span><h2>Explore the systems</h2></div><span className="cc-chip">Drag • zoom • tap regions</span></div><CortexBrain profile={profile} onSelect={setSelectedRegion}/>{selectedRegion&&<div className="cc-selected-info"><b>{selectedRegion.name}</b><span>{selectedRegion.function}</span><strong>{Math.round(selectedRegion.score)} signal</strong></div>}</div><aside className="cc-insights"><span className="cc-eyebrow">HIGHEST SIGNALS</span>{topRegions.map((r,i)=><div className="cc-region-row" key={r.id}><span>{String(i+1).padStart(2,'0')}</span><div><b>{r.name}</b><small>{r.function}</small></div><strong>{Math.round(r.score)}</strong><i><em style={{width:`${r.score}%`,background:`var(--${r.system},#38bdf8)`}}/></i></div>)}</aside></section>
   <section className="cc-dual"><div className="cc-panel"><span className="cc-eyebrow">POSSIBLE SUPERPOWERS TO NOTICE</span><h2>Strengths worth looking for</h2><p>These are prompts for reflection—not strengths inferred from adversity.</p>{SUPERPOWERS.map(([id,title,text])=><div className="cc-insight-row" key={id}><i>✦</i><div><b>{title}</b><span>{text}</span></div></div>)}</div><div className="cc-panel warm"><span className="cc-eyebrow">KRYPTONITES TO UNDERSTAND</span><h2>Friction worth designing around</h2><p>Common patterns associated with sustained stress; none is a diagnosis.</p>{KRYPTONITES.map(([id,title,text])=><div className="cc-insight-row" key={id}><i>⚡</i><div><b>{title}</b><span>{text}</span></div></div>)}</div></section>
   <section className="cc-priority"><div><span className="cc-eyebrow">PRIORITY FOCUS PLAN</span><h2>Start where leverage is highest.</h2></div><div className="cc-priority-grid"><article><span>01</span><h3>Regulate</h3><p>Protect sleep rhythm, reduce sensory load, and build repeatable grounding practices before high-demand moments.</p></article><article><span>02</span><h3>Understand</h3><p>Name triggers, body signals, and context. Treat patterns as information rather than identity.</p></article><article><span>03</span><h3>Build</h3><p>Design routines, relationships, and environments that make your strengths easier to access consistently.</p></article></div></section>
   <footer className="cc-report-foot"><b>◇ Cortex Compass</b><span>Research-informed educational reflection based on self-report. Not a diagnosis, scan, prognosis, or medical advice.</span><span>Utlyze • People know more.</span></footer>
 </main>;
}
