import React from 'react';
import CortexBrand from './CortexBrand';
export function JourneyRail({active='context'}) {
 const steps=[['context','Your context'],['experiences','Your experiences'],['patterns','Your patterns'],['reports','Your field guide']];
 return <ol className="cc-journey-rail" aria-label="Reflection journey">{steps.map(([id,label],i)=><li key={id} aria-current={id===active?'step':undefined}><span aria-hidden="true">0{i+1}</span><b>{label}</b></li>)}</ol>;
}
export function AtlasHeading(){return <div className="cc-atlas-heading"><span>THE CORTEX ATLAS</span><span>26 teaching regions <i aria-hidden="true">✦</i> one connected system</span></div>;}
export function FieldGuideIntro({onReports,onResearch,historyCount,insightCount}) {
 return <>
 <section className="cc-method-strip" aria-label="Inside your reflection"><div><b>{historyCount}</b><span>Optional history prompts</span></div><div><b>{insightCount}</b><span>Present-day observations</span></div><div><b>02</b><span>Distinct report editions</span></div><p>A little curiosity.<br/><em>A wider perspective.</em></p></section>
 <section className="cc-field-intro" aria-labelledby="field-intro-title"><div className="cc-field-philosophy"><span className="cc-eyebrow">YOUR EXPERIENCE IS MORE THAN A LABEL</span><h2 id="field-intro-title">A compass.<br/><em>Not a verdict.</em></h2><p>Explore your history, recognize the patterns you notice today, and see where research offers context—and where it does not.</p><div className="cc-field-principle"><span aria-hidden="true">01</span><p><b>Start with your experience.</b> Developmental context comes before calendar ages. Every question is optional.</p></div><div className="cc-field-principle"><span aria-hidden="true">02</span><p><b>Keep the evidence in view.</b> Observations, research, hypotheses and unknowns stay visibly separate.</p></div><div className="cc-field-principle"><span aria-hidden="true">03</span><p><b>Take the useful parts with you.</b> Choose a personal field guide or the full scientific breakdown.</p></div><button type="button" className="cc-field-link" onClick={onResearch}>Explore the research & methods <span aria-hidden="true">↗</span></button></div>
 <div className="cc-field-editions"><div className="cc-editions-caption"><span>TWO WAYS TO SEE YOUR PATTERNS</span><span aria-hidden="true">N ↗</span></div><article className="cc-edition cc-edition-personal"><div className="cc-edition-top"><img src="/brand/logo-mark-dark.svg" width="48" height="48" alt=""/><span>EDITION 01 / THE PERSONAL VIEW</span></div><h3>Superhero<br/><em>Report</em></h3><p>Possible strengths. Real-world friction.<br/>Support that matters to you.</p><div className="cc-edition-index"><span>SUPERPOWERS</span><span>KRYPTONITES</span><span>SUPPORT KIT</span></div><small>Two-page reflection · labels are metaphors</small></article>
 <article className="cc-edition cc-edition-scientific"><div className="cc-edition-top"><img src="/brand/logo-mark-light.svg" width="48" height="48" alt=""/><span>EDITION 02 / THE EVIDENCE VIEW</span></div><h3>Scientific <em>Report</em></h3><p>Follow the sources, developmental context, brain systems, and limits behind the guide.</p><div className="cc-edition-index"><span>ANATOMY</span><span>METHODS</span><span>UNCERTAINTY</span></div><small>Full research guide · not a brain assessment</small></article><button type="button" className="cc-primary" onClick={onReports}>Preview both report editions <span aria-hidden="true">↗</span></button></div></section>
 <section className="cc-field-promise"><img src="/brand/logo-mark-dark.svg" width="90" height="90" alt=""/><div><span className="cc-eyebrow">CURIOUS BY DESIGN. CAREFUL BY PRINCIPLE.</span><h2>Keep what fits.<br/><em>Question what doesn’t.</em></h2><p>No brain scan. No fixed identity. No pressure to make a painful experience into a positive story.</p></div><span className="cc-promise-coordinate" aria-hidden="true">CORTEX / COMPASS<br/>UNDERSTAND · REFLECT · PROGRESS</span></section>
 </>;
}
export function SiteSignature(){return <div className="cc-site-signature"><CortexBrand/><span>Understand · Reflect · Progress</span><small>An educational reflection by Utlyze</small></div>;}
