import React from 'react';
import {DEVELOPMENT_STUDIES,MATURATION_SYSTEMS,DEVELOPMENT_REVIEW} from '../data/developmentEvidence.mjs';
export function DevelopmentStudy({study}) {
 return <article className="cc-development-study" data-development-study={study.id}><span className="cc-eyebrow">{study.kind}</span><h3><a href={study.url} target="_blank" rel="noreferrer">{study.label}</a></h3><p className="cc-small-note">DOI: {study.doi} · Review: {DEVELOPMENT_REVIEW}</p><dl>{[['Participants',study.sample],['Developmental measurement',study.marker],['Stimulus / exposure',study.stimulus],['Outcome actually measured',study.response],['Interaction or stratification',study.moderation]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p><b>Finding:</b> {study.finding}</p><p><b>Sex / gender interpretation:</b> {study.sex}</p><p className="cc-development-boundary"><b>Limits:</b> {study.limit}</p>{study.correction&&<a href={study.correction} target="_blank" rel="noreferrer">Published author correction</a>}</article>;
}
export function MaturationSystems(){return <div className="cc-maturation-systems">{MATURATION_SYSTEMS.map(s=><article key={s.id} data-maturation-system={s.id}><h3>{s.title}</h3><p>{s.process}</p><p className="cc-small-note">{s.boundary}</p><p className="cc-development-citations">{s.sources.map(id=>{const e=DEVELOPMENT_STUDIES.find(x=>x.id===id);return <a key={id} href={e.url} target="_blank" rel="noreferrer">{e.label}</a>;})}</p></article>)}</div>;}
export default function DevelopmentResearch({full=false}) {
 return <section className={`cc-development-research ${full?'full':''}`} aria-label="Maturation and sex/gender research">
 <span className="cc-eyebrow">MATURATION-LED RESEARCH GUIDE</span><h2>Sensitive periods: developmental processes, not age bands</h2><p>A sensitive period concerns changing responsiveness in a particular system, to a particular experience or stimulus. This guide is organized by developmental process. It does not assign an individual opening or closing date.</p>
 <div className="cc-maturation-contract"><div><b>Reported context</b><span>Developmental stage, response, support, and source.</span></div><div><b>Research measurement</b><span>Puberty, hormones, circuit properties, or task response.</span></div><div><b>Individual inference</b><span>Not established without suitable measurements and validation.</span></div></div>
 <p className="cc-development-boundary">Pubertal development is informative, but is not identical to brain maturation. A birthday, gender identity, skill, diagnosis, or recalled milestone cannot substitute for a region-specific brain measurement. Calendar ages remain optional historical notes and never select a sensitive window in this app.</p>
 <MaturationSystems/>
 <h3>Read the specific stimulus–response relationship</h3><p>For example, Church et al. compared negative and neutral images under different regulation instructions. Some sex-related contrasts changed direction between conditions. That supports recording the actual task and stimulus, not assigning a general “more sensitive” sex.</p><p><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC12271767/" target="_blank" rel="noreferrer">Church et al. (2025): primary study</a></p>
 <p className="cc-small-note">A significant association in one group and a nonsignificant association in another does not by itself demonstrate a group difference. Sex-stratified morphology is not a stimulus-response experiment. Gender, assigned sex and hormone measures are kept distinct. The studies retain their actual age covariates and limitations even though the questionnaire is stage-first.</p>
 {full?<div className="cc-development-study-list">{DEVELOPMENT_STUDIES.map(study=><DevelopmentStudy key={study.id} study={study}/>)}</div>:<details><summary>Read all {DEVELOPMENT_STUDIES.length} developmental and sex/gender studies</summary><div className="cc-development-study-list">{DEVELOPMENT_STUDIES.map(study=><DevelopmentStudy key={study.id} study={study}/>)}</div></details>}
 </section>;
}
