import {readFileSync,writeFileSync} from 'node:fs';
const catalog=JSON.parse(readFileSync(new URL('../src/data/anatomyRegions.json',import.meta.url),'utf8'));
const regions=catalog.regions.map(r=>({...r,name:r.label,label:r.short||r.label}));
const ids=new Set(regions.map(r=>r.id));
if(ids.size!==regions.length)throw new Error('Duplicate region IDs');
for(const r of regions)for(const id of r.members||[])if(!ids.has(id))throw new Error('Missing group member: '+id);
const text='// Generated by scripts/sync-anatomy.mjs; edit anatomyRegions.json.\n'+
  `export const ANATOMY_VERSION=${JSON.stringify(catalog.version)};\n`+
  `export const ANATOMY_SOURCES=${JSON.stringify(catalog.sources,null,2)};\n`+
  `export const REGIONS=${JSON.stringify(regions,null,2)};\n`+
  'export const REGION_BY_ID=Object.fromEntries(REGIONS.map(r=>[r.id,r]));\n';
const path=new URL('../src/data/anatomyCatalog.mjs',import.meta.url);
if(process.argv.includes('--check')){
  if(readFileSync(path,'utf8')!==text)throw new Error('Catalog exports out of date');
}else writeFileSync(path,text);
console.log(`${regions.length} anatomy topics synchronized`);
