import React,{useState} from 'react';
import {saveDevicePortrait,deleteDevicePortrait} from '../../utils/neurohero/portraitDevice.mjs';
import {compileImagePrompt} from '../../utils/neurohero/portraitBrief.mjs';
export default function DevicePortraitControls({profile,choices,asset,onAsset}){
 const [consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const upload=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;setBusy(true);setMessage('');try{const next=await saveDevicePortrait(file,consent);onAsset(next);if(asset)await deleteDevicePortrait(asset);setMessage('Artwork saved only in this browser. Save your profile in the overview to keep it linked after reopening.');}catch(err){setMessage(err.message);}finally{setBusy(false);}};
 const download=()=>{const url=URL.createObjectURL(new Blob([compileImagePrompt(profile,choices)],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='Cortex-Compass-Hero-Visual-Brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="nh-image-availability"><h2>Your artwork, kept with your report</h2><p>Paid AI portraits and cloud accounts are not connected in this release. No private answers are sent to an image provider.</p><button className="cc-secondary" onClick={download}>Export the visual brief</button><label className="nh-image-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Save chosen artwork in this browser only. Use an image you have permission to use; it will not be uploaded.</label><input aria-label="Choose device portrait" type="file" accept="image/png,image/jpeg,image/webp" disabled={!consent||busy} onChange={upload}/>{asset&&<button className="cc-secondary" disabled={busy} onClick={async()=>{try{await deleteDevicePortrait(asset);onAsset(null);setMessage('Device portrait deleted. Save your profile again to update its reference.');}catch(err){setMessage(err.message);}}}>Delete this device portrait</button>}{message&&<p role="status">{message}</p>}</section>;
}
