import React,{useMemo,useState} from 'react';
import CortexBrand from '../CortexBrand';
import {HERO_PROCESSES,PROCESS_CHOICES,COUNTER_CHOICES} from '../../data/neurohero/processes.mjs';
import {buildHeroProfile,normalizeHeroAnswers} from '../../utils/neurohero/engine.mjs';
const DOMAIN_LABELS={salience:'Notice',memory:'Remember',attention:'Orient',executive:'Decide',learning:'Learn',interoception:'Sense',regulation:'Recover',social:'Connect',creativity:'Create',integration:'Integrate',agency:'Choose',support:'Sustain'};
export default function NeuroheroLab({answers,onChange,onDone,onBack,selectedId='',onSelect}){
 const clean=normalizeHeroAnswers(answers),profile=useMemo(()=>buildHeroProfile(clean,selectedId),[answers,selectedId]),domains=[...new Set(HERO_PROCESSES.map(p=>p.domain))],[domain,setDomain]=useState(domains[0]);const visible=HERO_PROCESSES.filter(p=>p.domain===domain);
 const patch=(id,next)=>onChange({...clean,[id]:{...clean[id],...next}});const answered=Object.values(clean).filter(a=>a.value).length;
 return <main className="cc-shell nh-lab"><header className="cc-nav"><div className="cc-brand"><CortexBrand/></div><button className="cc-secondary" onClick={onBack}>Back to overview</button></header>
 <section className="nh-lab-head"><span className="cc-eyebrow">DEEP HERO ATLAS · OPTIONAL</span><h1>Find the combinations that feel like you.</h1><p>These are functional observations, not a hidden brain scan. Counterexamples matter: a pattern that often fails to fit will not be used to build your hero signature.</p><div className="nh-progress"><b>{answered} / {HERO_PROCESSES.length}</b><span>functional observations reviewed</span></div></section>
 <nav className="nh-domain-nav" aria-label="Hero atlas chapters">{domains.map(id=><button key={id} aria-pressed={domain===id} onClick={()=>setDomain(id)}>{DOMAIN_LABELS[id]||id}</button>)}</nav>
 <section className="nh-lab-grid"><div className="nh-process-list">{visible.map(p=><article className="nh-process" key={p.id} data-process={p.id}><span className="nh-process-domain">{DOMAIN_LABELS[p.domain]||p.domain}</span><h2>{p.title}</h2><p>{p.question}</p><div className="nh-choice-row">{PROCESS_CHOICES.map(([id,label])=><button key={id} aria-pressed={clean[p.id]?.value===id} onClick={()=>patch(p.id,{value:id})}>{label}</button>)}</div><details><summary>When does this description not fit?</summary><p>{p.counter}</p><div className="nh-choice-row counter">{COUNTER_CHOICES.map(([id,label])=><button key={id} aria-pressed={clean[p.id]?.counter===id} onClick={()=>patch(p.id,{counter:id})}>{label}</button>)}</div></details></article>)}</div>
 <aside className="nh-live-profile"><span className="cc-eyebrow">LIVE COMPOSITION</span>{profile.signature?<><h2>{profile.signature.name}</h2><label className="nh-signature-choice">Choose a supported signature<select aria-label="Hero signature" value={profile.signature.id} onChange={e=>onSelect?.(e.target.value)}>{profile.compositions.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><p className="nh-power">{profile.signature.power}</p><dl><div><dt>Best conditions</dt><dd>{profile.signature.conditions}</dd></div><div><dt>Watch for</dt><dd>{profile.signature.cost}</dd></div><div><dt>Signature move</dt><dd>{profile.signature.experiment}</dd></div></dl><small>{profile.signature.fitStatus==='tentative-fit'?'Some components have counterexamples or unreviewed counterexamples.':'All required descriptions fit the reported answers; the composition itself is an unvalidated editorial hypothesis.'}</small></>:<><h2>Your signature is still forming.</h2><p>Review more observations. Nothing is inferred from unanswered items or your adversity history.</p></>}{profile.alternates.length>0&&<div className="nh-alternates"><b>Other possible signatures</b>{profile.alternates.slice(0,4).map(x=><span key={x.id}>{x.name}</span>)}</div>}</aside></section>
 <p className="nh-local-note">Nothing is saved automatically. Use Save profile in the overview to keep these responses on this device.</p><section className="nh-lab-actions"><button className="cc-secondary" disabled={domains.indexOf(domain)===domains.length-1} onClick={()=>{setDomain(domains[domains.indexOf(domain)+1]);requestAnimationFrame(()=>document.querySelector('.nh-process h2')?.scrollIntoView({block:'center'}));}}>Next chapter →</button><button className="cc-secondary" onClick={onBack}>Back to overview</button><button className="cc-primary" onClick={onDone}>Build my hero field guide →</button></section></main>;
}
