import React,{useState,useEffect} from 'react';
import CortexBrand from '../CortexBrand';
import {PORTRAIT_OPTIONS,normalizePortraitChoices,compilePortraitBrief,compileImagePrompt} from '../../utils/neurohero/portraitBrief.mjs';
import {getDevicePortrait} from '../../utils/neurohero/portraitDevice.mjs';
import DevicePortraitControls from './DevicePortraitControls';
const LABELS={presentation:'Hero presentation',skinTone:'Skin tone',build:'Build',hair:'Hair',accessibility:'Visible accessibility detail',setting:'Setting'};
const pretty=value=>value.replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase());
export function HeroPortraitPlaceholder({profile,choices,asset,className=''}){
 const brief=compilePortraitBrief(profile,choices),[image,setImage]=useState({url:null,state:asset?'loading':'none'});
 useEffect(()=>{let active=true,url;setImage({url:null,state:asset?'loading':'none'});if(asset)getDevicePortrait(asset).then(async blob=>{if(!blob)throw new Error('Missing image');url=URL.createObjectURL(blob);const img=new Image();img.src=url;await img.decode();if(active)setImage({url,state:'ready'});else URL.revokeObjectURL(url);}).catch(()=>{if(active)setImage({url:null,state:'missing'});});return()=>{active=false;if(url)URL.revokeObjectURL(url);};},[asset?.id,asset?.sha256]);
 return <figure className={`nh-portrait ${className}`} data-theme={brief.theme} data-portrait-state={image.state}>{image.url?<img src={image.url} alt={`${brief.title} chosen fictional hero artwork`}/>:<div className="nh-portrait-placeholder" aria-label="Symbolic emblem, not a generated character"><img className="nh-emblem" src="/brand/logo-mark-light.svg" alt=""/><b>{brief.title}</b><small>{image.state==='loading'?'Loading saved artwork…':image.state==='missing'?'Saved image is not available on this device':'Symbolic edition'}</small></div>}<figcaption>{image.url?'Your saved device artwork · reused for printing':'Compass emblem · no AI portrait generated'}</figcaption></figure>;
}
export default function NeuroheroPortrait({profile,choices,onChange,asset,onAsset,onDone,onBack}){
 const clean=normalizePortraitChoices(choices),patch=(key,value)=>onChange({...clean,[key]:value});
 return <main className="cc-shell nh-portrait-studio"><header className="cc-nav"><div className="cc-brand"><CortexBrand/></div><button className="cc-secondary" onClick={onBack}>Back to hero atlas</button></header><section className="nh-portrait-shell"><div><span className="cc-eyebrow">PORTRAIT STUDIO · YOUR VISUAL CHOICE</span><h1>Choose how your hero shows up.</h1><p>Your visual choices do not change the scientific interpretation. Accepted artwork stays the same across repeat PDF exports.</p><div className="nh-portrait-controls">{Object.entries(PORTRAIT_OPTIONS).map(([key,values])=><label key={key}><span>{LABELS[key]}</span><select aria-label={LABELS[key]} value={clean[key]} onChange={e=>patch(key,e.target.value)}>{values.map(v=><option key={v} value={v}>{pretty(v)}</option>)}</select></label>)}</div><DevicePortraitControls profile={profile} choices={choices} asset={asset} onAsset={onAsset}/></div><aside><HeroPortraitPlaceholder profile={profile} choices={clean} asset={asset}/><details className="nh-brief"><summary>Review the minimal visual brief</summary><p>{compileImagePrompt(profile,choices)}</p><p>Only visual choices and approved symbolic motifs are included. History, diagnoses, sex/hormonal context and private answers are excluded.</p></details></aside></section><div className="nh-lab-actions"><button className="cc-secondary" onClick={onBack}>Back to hero atlas</button><button className="cc-primary" onClick={onDone}>Use this visual direction →</button></div></main>;
}
