import React from 'react';
import {PROCESS_CHOICES,COUNTER_CHOICES} from '../../data/neurohero/processes.mjs';
const response=(choices,id)=>choices.find(([v])=>v===id)?.[1]||'Not reviewed';
export function HeroSignature(){return null;}
export function HeroAuditBody({heroProfile}){
 const h=heroProfile?.signature;if(!heroProfile||!Object.keys(heroProfile.answers).length)return <p>The optional Deep Hero Atlas has not been completed. No functional or neurological properties are backfilled from history or demographic answers.</p>;
 return <div className="nh-evidence-audit"><h3>{h?h.name:'No composition currently selected'}</h3><p>{h?.power||'The necessary functional descriptions are not all endorsed. This is not evidence that the person lacks strengths.'}</p><p className="cc-report-boundary">All named combinations are editorial hypotheses. Citing component research does not validate the combination, establish an anatomical alteration, or provide an individual probability. Conditional advice is an experiment, not a treatment prescription.</p>
 <h3>How this signature was selected</h3><p>Only Often or Sometimes responses can supply a component. A frequent counterexample excludes it. Occasional counterexamples, or unreviewed counterexamples, make the fit tentative. The reader can select any currently supported combination. Default ordering counts Often responses, then uses fixed catalogue order; it is not a neurological score or an assessment of superiority.</p>
 {h&&<div className="nh-claim-chain">{h.parts.map(p=><article key={p.id}><b>{p.title}</b><p>Observation: {response(PROCESS_CHOICES,p.answer.value)}. Counterexample: {response(COUNTER_CHOICES,p.answer.counter)}.</p><p>Research links: {p.evidence.length?p.evidence.join(', '):'No direct source assigned; editorial construct.'}</p><p>Brain/circuit property in this reader: <strong>unmeasured</strong>.</p></article>)}</div>}
 <h3>Complete functional observation ledger</h3><table className="cc-observation-table nh-observation-table"><thead><tr><th>Process</th><th>Response</th><th>Counterexample</th></tr></thead><tbody>{heroProfile.processes.map(p=><tr key={p.id}><th scope="row">{p.title}</th><td>{response(PROCESS_CHOICES,p.answer.value)}</td><td>{response(COUNTER_CHOICES,p.answer.counter)}</td></tr>)}</tbody></table>
 <h3>Other eligible compositions</h3><p>{heroProfile.alternates.length?heroProfile.alternates.map(c=>c.name).join(' · '):'None currently meet the inclusion rules.'}</p><h3>Counterexamples retained</h3><p>{heroProfile.counterexamples.length?heroProfile.counterexamples.map(p=>p.title).join('; '):'No frequent counterexample is present for an endorsed component. Unreviewed counterexamples are not evidence of consistency.'}</p>
 <h3>Research context and its limits</h3><p>This is a curated evidence map, not a new pooled meta-analysis. Source tasks, modality, populations and overlapping cohorts cannot be combined into an invented synergy coefficient. A study-specific finding does not establish that a person who endorsed a related statement has the studied neurological alteration.</p><div className="nh-evidence-records">{heroProfile.evidence.map(e=><article key={e.id} data-neurohero-source={e.id}><span>{e.kind}</span><h3><a href={e.url} target="_blank" rel="noreferrer">{e.label}</a></h3><p>{e.claim}</p><p><b>What this does not establish:</b> {e.boundary}</p><p className="cc-small-note">DOI: <a href={`https://doi.org/${e.doi}`} target="_blank" rel="noreferrer">{e.doi}</a>. Link role: related research context, not validation of a named hero. See the primary source for measurement and sampling details.</p></article>)}</div><p className="cc-small-note">{heroProfile.version} · {heroProfile.evidenceVersion}. The 27 descriptions are not claimed to be independent dimensions or an exhaustive census of neural functioning.</p></div>;
}
