import HeroAtmosphere from './HeroAtmosphere';
import React from 'react';
import CortexBrand from '../CortexBrand';
import {HeroPortraitPlaceholder} from './NeuroheroPortrait';
import {buildInsights} from '../../utils/insightProfile.mjs';
export function HeroStrengthsCard({heroProfile,portraitChoices,portraitAsset,demo}){
 const h=heroProfile.signature;return <div data-report="hero-card"><section className="cc-paper-page nh-card-page"><HeroAtmosphere asset={portraitAsset}/><div className="cc-paper-brand"><CortexBrand variant="paper"/></div>{demo&&<p className="cc-fictional">FICTIONAL SAMPLE · NOT YOUR RESULTS</p>}<span className="cc-eyebrow">A SIGNATURE YOU CAN MAKE YOUR OWN</span><h1>{h?.name||'Cortex Explorer'}</h1><HeroPortraitPlaceholder profile={heroProfile} choices={portraitChoices} asset={portraitAsset}/><p>{h?.power}</p><div className="nh-card-strengths">{h?.parts.map(p=><span key={p.id}>{p.title}</span>)}</div><p className="cc-small-note">A symbolic character based on reported patterns, not a measured neurological type. This card excludes history, biological-sex answers, counterexamples and demanding conditions.</p></section></div>;
}
export default function NeuroheroFieldGuide({heroProfile,portraitChoices,portraitAsset,insightAnswers={},demo}){
 const h=heroProfile.signature,insights=buildInsights(insightAnswers);if(!h)return null;
 return <div data-report="superhero" className="nh-field-guide"><section className="cc-paper-page nh-guide-page nh-hero-cover"><HeroAtmosphere asset={portraitAsset}/><div className="cc-paper-brand"><CortexBrand variant="paper"/></div>{demo&&<p className="cc-fictional">FICTIONAL SAMPLE · NOT YOUR RESULTS</p>}<span className="cc-eyebrow">SUPERHERO REPORT · YOUR CURRENT SIGNATURE</span><div className="nh-guide-hero"><div><h1>{h.name}</h1><p className="nh-guide-line">Your perspective.<br/>Your signature.</p><p>{h.power}</p><p className="cc-small-note">{h.fitStatus==='tentative-fit'?'A conditional fit: some counterexamples are present or have not been reviewed.':'The required component descriptions fit your current responses.'} You can choose another supported signature or revise your answers.</p></div><HeroPortraitPlaceholder profile={heroProfile} choices={portraitChoices} asset={portraitAsset}/></div><h2>The capabilities in your combination</h2><div className="nh-guide-powers">{h.parts.map(p=><article key={p.id}><span>✦</span><h3>{p.title}</h3><p>{p.assets.join(' · ')}</p><small>{p.answer.value==='often'?'Often':'Sometimes'} true · self-reported</small></article>)}</div><div className="nh-guide-move"><span className="cc-eyebrow">YOUR SIGNATURE MOVE</span><p>{h.experiment}</p></div><p className="cc-small-note">This name and its combined possibilities are editorial hypotheses. Research context and the observation ledger appear in the Scientific Report. No scan, diagnosis or personal neural alteration was inferred.</p></section>
 <section className="cc-paper-page nh-guide-page"><div className="cc-paper-brand"><CortexBrand variant="paper"/></div><span className="cc-eyebrow">GET MORE FROM WHAT YOU NOTICE</span><h2>Conditions that help you use it.</h2><p className="nh-guide-lead">{h.conditions}</p><div className="nh-guide-pair"><article><span className="cc-eyebrow">POSSIBLE KRYPTONITE</span><h3>What to watch for</h3><p>{h.cost}</p><small>A proposed trade-off to check, not a difficulty automatically assigned to you.</small></article><article><span className="cc-eyebrow">WHAT YOU ACTUALLY REPORTED</span><h3>Friction, in your terms</h3>{insights.frictions.length?<p>{insights.frictions.map(p=>p.title).join(' · ')}</p>:<p>No current friction was endorsed in the separate reflection. This does not establish its absence.</p>}<small>Counterexamples can qualify or remove a candidate signature; they never lower your worth or become hidden diagnoses.</small></article></div><h2>Your support kit</h2><p>{insights.resources.length?insights.resources.map(p=>p.title).join(' · '):'Current resources were not endorsed in the optional reflection. Their availability remains unknown.'}</p><p className="cc-small-note">These are reported supports, not calculated amplifiers or buffering percentages.</p><div className="nh-guide-move"><span className="cc-eyebrow">ONE REAL-WORLD QUEST</span><h3>Try the move. Keep the counterexamples.</h3><p>{h.experiment}</p><p>Choose a small, low-stakes situation. Notice what helped, what it cost, and when the description did not fit. Change the story when the evidence changes.</p></div><p className="cc-report-boundary">Strengths, difficulty, practice and support can coexist. This report does not claim that harm was necessary or that you owe a positive interpretation of it.</p><p className="cc-small-note">{heroProfile.version} · {heroProfile.evidenceVersion} · No paid generation occurs when you print.</p></section></div>;
}
