import {compileXaiPortraitPrompt} from '../../utils/neurohero/xaiVisual.mjs';
import React,{useEffect,useRef,useState} from 'react';
import {normalizePortraitChoices,compileImagePrompt} from '../../utils/neurohero/portraitBrief.mjs';
import {saveDevicePortrait} from '../../utils/neurohero/portraitDevice.mjs';
const API='/api/portraits';
const messages={edition_deleted:'This visual edition was deleted. Choose another edition before creating a new portrait.',sign_in_required:'Sign in to your private portrait workspace.',access_not_available:'That access pass is not available. Check the pass and try again.',portrait_allowance_used:'This portrait pass has used its generation allowance. Saved portraits remain available.',pilot_budget_reached:'The portrait pilot has reached its current generation budget. Saved portraits are still available.',try_later:'Too many sign-in attempts. Please try again later.',image_filtered:'The image provider did not approve this image. It will not be automatically retried.',provider_outcome_unknown:'The provider outcome is uncertain. No automatic paid retry will be made.',provider_access_denied:'The image service is temporarily unavailable.',service_not_configured:'AI portraits are not enabled on this deployment.'};
async function api(path,method='GET',body){const r=await fetch(API+path,{method,credentials:'same-origin',cache:'no-store',headers:{...(body?{'Content-Type':'application/json'}:{}),...(method!=='GET'?{'X-Cortex-Request':'portrait-v1'}:{})},...(body?{body:JSON.stringify(body)}:{})});let data;try{data=await r.json();}catch{throw new Error('AI portrait service is unavailable on this deployment.');}if(!r.ok)throw new Error(messages[data.error]||'The portrait request could not be completed. No automatic paid retry was made.');return data;}
export default function XaiPortraitControls({profile,choices,onAsset}){
 const [service,setService]=useState(null),[pass,setPass]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[selected,setSelected]=useState(null),[imageURL,setImageURL]=useState(''),[edition,setEdition]=useState(0);
 const lock=useRef(false),requests=useRef(new Map()),alive=useRef(true);const spec={heroId:profile?.signature?.id||'unclassified',choices:normalizePortraitChoices(choices),edition};const specKey=JSON.stringify(spec);
 const refresh=async()=>{const next=await api('/status');if(alive.current)setService(next);return next;};
 useEffect(()=>{alive.current=true;refresh().catch(()=>{if(alive.current)setService({available:false});});return()=>{alive.current=false;};},[]);
 useEffect(()=>{setSelected(null);setImageURL('');setConsent(false);},[specKey]);
 const pending=service?.jobs?.some(j=>['queued','running'].includes(j.status));
 useEffect(()=>{if(!pending)return;const start=Date.now();const timer=setInterval(()=>{if(Date.now()-start>240000){clearInterval(timer);setNotice('Generation is taking longer than expected. Refresh the library to check it; no second request was sent.');return;}refresh().catch(()=>{});},3000);return()=>clearInterval(timer);},[pending]);
 useEffect(()=>{if(!selected)return;const current=service?.jobs?.find(j=>j.id===selected.id);if(current&&current.status!==selected.status)setSelected(current);},[service,selected]);
 useEffect(()=>{if(selected?.status!=='ready'){setImageURL('');return;}let disposed=false,url='';fetch(`${API}/jobs/${selected.id}/image`,{credentials:'same-origin',cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Sign in again to view this private portrait.');const blob=await r.blob();url=URL.createObjectURL(blob);if(!disposed)setImageURL(url);else URL.revokeObjectURL(url);}).catch(e=>{if(!disposed)setNotice(e.message);});return()=>{disposed=true;if(url)URL.revokeObjectURL(url);};},[selected?.id,selected?.status]);
 const action=async fn=>{if(lock.current)return;lock.current=true;setBusy(true);setNotice('');try{await fn();}catch(e){setNotice(e.message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
 const login=()=>action(async()=>{await api('/session','POST',{pass:pass.trim()});setPass('');await refresh();setNotice('Private portrait workspace unlocked. Questionnaire answers remain on this device.');});
 const generate=()=>action(async()=>{if(!consent)throw new Error('Review and accept the visual-brief consent first.');let id=requests.current.get(specKey);if(!id){id=crypto.randomUUID();requests.current.set(specKey,id);}const result=await api('/jobs','POST',{spec,requestId:id,consent:true});setSelected(result.job);await refresh();setNotice(result.job.status==='ready'?'Your saved portrait is ready. No new image charge was triggered.':'Portrait queued. You may leave this panel and return to the library.');});
 const deleteImage=()=>action(async()=>{if(!window.confirm('Delete this portrait from the private cloud library? Existing device and PDF copies are unchanged.'))return;const result=await api(`/jobs/${selected.id}`,'DELETE');setSelected(null);setImageURL('');await refresh();setNotice(result.deletionPending?'Deletion requested. The in-progress result will not be retained.':'Cloud portrait deleted; device and PDF copies are unchanged.');});
 const useImage=()=>action(async()=>{const r=await fetch(`${API}/jobs/${selected.id}/image`,{credentials:'same-origin',cache:'no-store'});if(!r.ok)throw new Error('Unable to retrieve this private portrait.');const blob=await r.blob();const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))].map(v=>v.toString(16).padStart(2,'0')).join('');if(digest!==selected.sha256)throw new Error('Portrait integrity check failed; no image was saved.');const asset=await saveDevicePortrait(blob,true);onAsset({...asset,provider:'xAI',cloudId:selected.id});setNotice('xAI portrait added to your report and stored in this browser. Save your profile in the overview to preserve the link. Printing will reuse it.');});
 return <section className="nh-xai-panel" aria-label="xAI portrait generation"><span className="cc-eyebrow">XAI · YOUR PORTRAIT STUDIO</span><h2>Give your hero a face.</h2><p>Original, detailed anime-inspired artwork. Generate it once, choose it, and keep the same portrait in later reports.</p>
 {!service?.available?<p role="status">{service===null?'Checking portrait availability…':'The portrait service is unavailable right now. Ordinary reports and device artwork still work.'}</p>:!service.authenticated?<><p><b>Private portrait pilot.</b> Enter your portrait access pass. This is a restricted workspace, not public account registration.</p><label className="nh-xai-access">Portrait access pass<input type="password" autoComplete="off" spellCheck={false} value={pass} maxLength={64} onChange={e=>setPass(e.target.value)}/></label><button className="cc-primary" disabled={busy||!pass.trim()} onClick={login}>Unlock portrait studio</button></>:<>
 <div className="nh-xai-account"><b>{service.remaining} generation{service.remaining===1?'':'s'} remaining</b><button className="cc-secondary" disabled={busy} onClick={()=>action(async()=>{await api('/session','DELETE');setSelected(null);setImageURL('');await refresh();})}>Sign out of portraits</button></div>
 <details className="nh-brief"><summary>Review the exact visual brief</summary><p>{compileXaiPortraitPrompt(profile,choices)}</p><p>Only these appearance choices and public hero motifs go to xAI—not your history, questionnaire answers, research variables, name, or contact details.</p></details>
 <label className="nh-image-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Send this visual brief to xAI and store the resulting portrait privately in Cortex Compass. This is fictional art, not a representation of measured brain anatomy.</label>
 <p className="cc-small-note">xAI states API data is not used for training without permission and is normally retained for 30 days for abuse auditing. <a href="https://docs.x.ai/developers/faq/security" target="_blank" rel="noreferrer">Provider privacy details</a>. Your access pass controls this workspace; keep it private.</p>
 <div className="cc-actions"><button className="cc-primary" disabled={busy||!consent||service.remaining<1} onClick={generate}>Create my xAI portrait</button><button className="cc-secondary" disabled={busy} onClick={()=>action(refresh)}>Refresh my portraits</button>{service.remaining>0&&<button className="cc-secondary" disabled={busy||service.remaining<1} onClick={()=>{if(window.confirm('Choose another visual edition? Creating it will use one generation from your allowance.')){setEdition(e=>e+1);setNotice('New visual edition selected. Review and consent before generating.');}}}>Choose another edition</button>}</div>
 <div className="nh-xai-library" aria-label="Private portrait library">{service.jobs?.map(j=><button type="button" className="cc-secondary" key={j.id} aria-pressed={selected?.id===j.id} onClick={()=>setSelected(j)}>{j.spec?.heroId?.replaceAll('_',' ')||'Portrait'} · {j.status}</button>)}</div>
 {selected&&<div className="nh-xai-preview" data-xai-status={selected.status}>{imageURL&&<img src={imageURL} alt="Private fictional hero portrait generated by xAI"/>}<p role="status">{selected.status==='failed'?(messages[selected.error]||'The image could not be completed; no automatic retry will occur.'):selected.status}</p>{selected.status==='ready'&&<><button className="cc-primary" disabled={busy||!imageURL} onClick={useImage}>Use this portrait in my report</button><p className="cc-small-note">This saves an offline copy in this browser. Save your profile afterward to keep it linked.</p></>}<button className="cc-secondary" disabled={busy} onClick={deleteImage}>Delete cloud portrait</button></div>}
 </>}{notice&&<p className="nh-xai-notice" role="status">{notice}</p>}</section>;
}
